import type {
  DesignDiagramModelSpec,
  CodeGenerationSpec,
  CodeBusinessLogic,
  CodeRunSnapshot,
  CodeUiMockup,
  DesignRunSnapshot,
  DesignModelTraceabilityEntry,
  DesignSvgArtifact,
  DiagramError,
  DiagramModelSpec,
  RequirementModelTraceabilityEntry,
  RequirementBaseline,
  RequirementQualityReport,
  AtomicRequirement,
  RunSnapshot,
  RunStage,
  RunStatus as ContractRunStatus,
  SvgArtifact,
} from "@uml-platform/contracts";
import type { DiagramType } from "../diagram/model";
import type { DesignDiagramType } from "../diagram/model";
import type { RequirementRule } from "../requirement-rule/model";

export type WorkspaceRunSnapshot = RunSnapshot;
export type WorkspaceDesignRunSnapshot = DesignRunSnapshot;
export type WorkspaceCodeRunSnapshot = CodeRunSnapshot;
export type RunStatus = "idle" | ContractRunStatus;

export interface ManualModelEditStatus {
  status: "dirty" | "rerendered";
  warning: string | null;
  editedAt: string;
  rerenderedAt?: string;
}

export interface RequirementReviewCandidate {
  ruleId: string;
  beforeRequirement: AtomicRequirement;
  afterRequirement: AtomicRequirement | null;
  repairRationale: string | null;
  blockingReasons: string[];
  status: "pending" | "accepted" | "rejected" | "failed";
  errorMessage: string | null;
  createdAt: string;
}

export interface AutoGeneratedUpstreamReview {
  id: string;
  artifactType: "requirement-rule" | "requirement-model" | "design-model";
  artifactId: string;
  label: string;
  reason: string;
  sourceRunId: string | null;
  status: "pending" | "accepted" | "dismissed";
  createdAt: string;
}

export interface WorkspaceRecord {
  id: string;
  name: string;
  requirementText: string;
  selectedDiagramTypes: DiagramType[];
  rules: RequirementRule[];
  requirementBaseline: RequirementBaseline | null;
  requirementQualityReport: RequirementQualityReport | null;
  requirementReviewCandidates: Record<string, RequirementReviewCandidate>;
  autoGeneratedUpstreamReviews: Record<string, AutoGeneratedUpstreamReview>;
  models: Partial<Record<DiagramType, DiagramModelSpec>> &
    Record<string, DiagramModelSpec | undefined>;
  requirementModelTraceability: RequirementModelTraceabilityEntry[];
  generatedDiagramTypes: DiagramType[];
  plantUml: Partial<Record<DiagramType, string>> & Record<string, string | undefined>;
  svgArtifacts: Partial<Record<DiagramType, SvgArtifact>> &
    Record<string, SvgArtifact | undefined>;
  diagramErrors: Partial<Record<DiagramType, DiagramError>> &
    Record<string, DiagramError | undefined>;
  selectedDesignDiagramTypes: DesignDiagramType[];
  designModels: Record<string, DesignDiagramModelSpec>;
  designModelTraceability: DesignModelTraceabilityEntry[];
  generatedDesignDiagramTypes: DesignDiagramType[];
  designPlantUml: Record<string, string>;
  designSvgArtifacts: Record<string, DesignSvgArtifact>;
  designDiagramErrors: Record<string, DiagramError>;
  manualModelEditStatus: Record<string, ManualModelEditStatus>;
  codeSpec: CodeGenerationSpec | null;
  codeBusinessLogic: CodeBusinessLogic | null;
  codeFiles: Record<string, string>;
  codeEntryFile: string | null;
  codeDependencies: Record<string, string>;
  codeUiMockup: CodeUiMockup | null;
  codeAgentPlan: string[];
  codeSkills: CodeRunSnapshot["selectedCodeSkills"];
  codeSkillDiagnostics: CodeRunSnapshot["skillDiagnostics"];
  codeSkillResourcePlan: CodeRunSnapshot["skillResourcePlan"];
  codeSkillContext: CodeRunSnapshot["codeSkillContext"];
  codeDiagnostics: CodeRunSnapshot["diagnostics"];
  requirementInputFingerprint: string | null;
  diagramInputFingerprints: Partial<Record<DiagramType, string>>;
  designInputFingerprints: Record<string, string>;
  rulesVersion: number;
  rulesBasedOnTextVersion: number | null;
  diagramVersions: Partial<Record<DiagramType, number>>;
  currentStage: RunStage | null;
  runStatus: RunStatus;
  runProgress: number;
  runMessage: string | null;
  errorMessage: string | null;
}
