// Implements the browser HTTP workspace repository and project-scoped persistence adapter.
import type {
  DesignSvgArtifact,
  OnlyOfficeUiTheme,
  RepairRequirementRuleRequest,
  RepairRequirementRulesRequest,
  RequirementBaseline,
  RunEvent,
  SvgArtifact,
} from "@uml-platform/contracts";
import {
  getRequirementModelId,
  type DiagramType,
} from "../../entities/diagram/model";
import type { WorkspaceRecord } from "../../entities/workspace/model";
import type { RequirementRule } from "../../entities/requirement-rule/model";
import { ApiClientError, requestJson } from "../api-client";
import {
  createRunHistoryTitle,
  loadRunHistory,
  type RunHistorySnapshot,
} from "../../entities/run-history";
import type {
  StartCodeRunInput,
  StartDesignRunInput,
  StartDocumentRunInput,
  StartRunInput,
} from "./start-inputs";
import {
  PROJECT_REQUIRED_MESSAGE,
  normalizeProjectId,
  requireProjectScope,
  withProjectHeaders,
} from "./project-scope";
import {
  normalizeProjectHistoryResponse,
  projectRunSummaryToHistoryItem,
  type ProjectRunDetailResponse,
  type ProjectRunsResponse,
} from "./project-history";
import {
  readCodeRunSnapshot,
  readDesignRunSnapshot,
  readDocumentRunSnapshot,
  readRunSnapshot,
  subscribeToCodeRunEvents,
  subscribeToDesignRunEvents,
  subscribeToDocumentRunEvents,
  subscribeToRequirementRunEvents,
} from "./run-subscriptions";
import {
  downloadDocumentFile,
  downloadDocumentRunFile,
  listDocumentLibraryItems,
  postRunReviewDecision,
  readOnlyOfficeEditorConfig,
  readRunEvidencePackage,
} from "./document-api";
import {
  applySnapshotToWorkspace,
  cloneWorkspace,
  createEmptyWorkspace,
  mergeWorkspaceState,
  restoreSnapshotToWorkspace,
  stableWorkspaceState,
} from "./workspace-state";
import {
  renderPlantUmlRequest,
  renderStructuredModelRequest,
  repairRequirementRuleRequest,
  repairRequirementRulesRequest,
  startCodeRunRequest,
  startDesignRunRequest,
  startDocumentRunRequest,
  startRequirementRunRequest,
  testProviderSettingsRequest,
} from "./run-actions-api";
import type {
  RequirementRulesUpdateMetadata,
  WorkspaceRepository,
} from "./types";

interface WorkspaceRepositoryOptions {
  projectId?: string | null;
}

type ProjectWorkspaceResponse = {
  projectId: string;
  version: number;
  state?: Partial<WorkspaceRecord>;
  updatedAt?: string;
  updatedByUserId?: string | null;
  sourceRunId?: string | null;
};

type ProjectAccessResponse = {
  capabilities?: string[];
};

export function createHttpWorkspaceRepository(
  options: WorkspaceRepositoryOptions = {},
): WorkspaceRepository {
  const projectId = normalizeProjectId(options.projectId);
  let localRequirementText = "";
  let localRequirementRules: RequirementRule[] = [];
  let localRequirementBaseline: RequirementBaseline | null = null;
  let localRequirementReviewCandidates: WorkspaceRecord["requirementReviewCandidates"] =
    {};
  let localAutoGeneratedUpstreamReviews: WorkspaceRecord["autoGeneratedUpstreamReviews"] =
    {};
  let localRequirementInputFingerprint: WorkspaceRecord["requirementInputFingerprint"] =
    null;
  let localRulesVersion = 0;
  let localRulesBasedOnTextVersion: WorkspaceRecord["rulesBasedOnTextVersion"] =
    null;
  let projectWorkspace: WorkspaceRecord | null = null;
  let projectWorkspaceVersion = 0;
  let projectWorkspaceUpdateQueue: Promise<unknown> = Promise.resolve();
  let projectWorkspaceSaveError: unknown = null;

  async function loadProjectWorkspace() {
    const scopedProjectId = requireProjectScope(projectId);
    const response = await requestJson<ProjectWorkspaceResponse>(
      `/api/projects/${encodeURIComponent(scopedProjectId)}/workspace`,
      withProjectHeaders(scopedProjectId, {
        errorMessage: "读取项目工作台失败",
      }),
    );
    projectWorkspaceVersion = response.version;
    projectWorkspace = mergeWorkspaceState(response.state);
    await hydrateEmptyProjectWorkspaceFromLatestRun();
    return cloneWorkspace(projectWorkspace);
  }

  async function ensureProjectWorkspace() {
    if (projectWorkspace) return projectWorkspace;
    await loadProjectWorkspace();
    return projectWorkspace ?? createEmptyWorkspace();
  }

  async function saveProjectWorkspace(
    workspace: WorkspaceRecord,
    sourceRunId?: string | null,
  ) {
    const scopedProjectId = requireProjectScope(projectId);
    const response = await requestJson<ProjectWorkspaceResponse>(
      `/api/projects/${encodeURIComponent(scopedProjectId)}/workspace`,
      withProjectHeaders(scopedProjectId, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          baseVersion: projectWorkspaceVersion,
          state: stableWorkspaceState(workspace),
          sourceRunId: sourceRunId ?? null,
        }),
        errorMessage: "保存项目工作台失败",
      }),
    );
    projectWorkspaceVersion = response.version;
    projectWorkspace = mergeWorkspaceState(response.state);
    return cloneWorkspace(projectWorkspace);
  }

  async function updateProjectWorkspace(
    mutate: (workspace: WorkspaceRecord) => void,
    sourceRunId?: string | null,
  ) {
    const runUpdate = async () => {
      const current = await ensureProjectWorkspace();
      const next = cloneWorkspace(current);
      mutate(next);
      try {
        return await saveProjectWorkspace(next, sourceRunId);
      } catch (error) {
        if (!(error instanceof ApiClientError) || error.status !== 409) {
          throw error;
        }
        await loadProjectWorkspace();
        const latest = cloneWorkspace(
          projectWorkspace ?? createEmptyWorkspace(),
        );
        mutate(latest);
        return saveProjectWorkspace(latest, sourceRunId);
      }
    };
    const queuedUpdate = projectWorkspaceUpdateQueue.then(runUpdate, runUpdate);
    projectWorkspaceUpdateQueue = queuedUpdate.then(
      () => {
        projectWorkspaceSaveError = null;
      },
      (error) => {
        projectWorkspaceSaveError = error;
      },
    );
    return queuedUpdate;
  }

  async function waitForProjectWorkspaceSaves() {
    await projectWorkspaceUpdateQueue;
    if (projectWorkspaceSaveError) {
      throw projectWorkspaceSaveError;
    }
  }

  async function readProjectRunDetail(runId: string) {
    const scopedProjectId = requireProjectScope(projectId);
    return requestJson<ProjectRunDetailResponse>(
      `/api/projects/${encodeURIComponent(scopedProjectId)}/runs/${encodeURIComponent(runId)}`,
      withProjectHeaders(scopedProjectId, {
        errorMessage: "读取项目运行详情失败",
      }),
    );
  }

  async function restoreProjectWorkspaceFromRun(runId: string) {
    const scopedProjectId = requireProjectScope(projectId);
    const response = await requestJson<ProjectWorkspaceResponse>(
      `/api/projects/${encodeURIComponent(scopedProjectId)}/runs/${encodeURIComponent(runId)}/restore-workspace`,
      withProjectHeaders(scopedProjectId, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          mode: "restore",
        }),
        errorMessage: "恢复项目工作台快照失败",
      }),
    );
    projectWorkspaceVersion = response.version;
    projectWorkspace = mergeWorkspaceState(response.state);
    return cloneWorkspace(projectWorkspace);
  }

  async function readProjectRunHistoryItem(runId: string) {
    const detail = await readProjectRunDetail(runId);
    return projectRunSummaryToHistoryItem(detail.run, detail.snapshot ?? null);
  }

  async function readProjectRuns() {
    const scopedProjectId = requireProjectScope(projectId);
    return requestJson<ProjectRunsResponse>(
      `/api/projects/${encodeURIComponent(scopedProjectId)}/runs`,
      withProjectHeaders(scopedProjectId, {
        errorMessage: "读取项目运行历史失败",
      }),
    );
  }

  async function persistSnapshotAsProjectWorkspace(
    snapshot: RunHistorySnapshot,
    mode: "merge" | "restore" = "merge",
  ) {
    const current = await ensureProjectWorkspace();
    const next =
      mode === "restore"
        ? restoreSnapshotToWorkspace(current, snapshot)
        : applySnapshotToWorkspace(current, snapshot);
    try {
      return await saveProjectWorkspace(next, snapshot.runId);
    } catch (error) {
      if (!(error instanceof ApiClientError) || error.status !== 409) {
        throw error;
      }
      await loadProjectWorkspace();
      const latest = projectWorkspace ?? createEmptyWorkspace();
      return saveProjectWorkspace(
        mode === "restore"
          ? restoreSnapshotToWorkspace(latest, snapshot)
          : applySnapshotToWorkspace(latest, snapshot),
        snapshot.runId,
      );
    }
  }

  async function hydrateEmptyProjectWorkspaceFromLatestRun() {
    if (!projectWorkspace || projectWorkspace.requirementText.trim()) return;
    const runs = (await readProjectRuns()).runs ?? [];
    const candidates = runs
      .filter((run) => run.runId && run.snapshotAvailable && run.canRestore)
      .sort((left, right) => {
        const documentRank =
          Number(left.documentDownloadAvailable) -
          Number(right.documentDownloadAvailable);
        if (documentRank !== 0) return documentRank;
        const leftTime = Date.parse(
          left.completedAt ?? left.updatedAt ?? left.startedAt ?? "",
        );
        const rightTime = Date.parse(
          right.completedAt ?? right.updatedAt ?? right.startedAt ?? "",
        );
        return (
          (Number.isNaN(rightTime) ? 0 : rightTime) -
          (Number.isNaN(leftTime) ? 0 : leftTime)
        );
      });
    for (const run of candidates) {
      try {
        await restoreProjectWorkspaceFromRun(run.runId!);
      } catch (error) {
        if (
          !(error instanceof ApiClientError) ||
          (error.status !== 400 && error.status !== 403 && error.status !== 409)
        ) {
          throw error;
        }
        continue;
      }
      return;
    }
  }

  return {
    async getProjectCapabilities() {
      if (!projectId) return ["update_project", "start_runs"];
      const scopedProjectId = requireProjectScope(projectId);
      const response = await requestJson<ProjectAccessResponse>(
        `/api/projects/${encodeURIComponent(scopedProjectId)}`,
        withProjectHeaders(scopedProjectId, {
          errorMessage: "读取项目权限失败",
        }),
      );
      return response.capabilities ?? [];
    },

    async loadWorkspace() {
      if (projectId) {
        return loadProjectWorkspace();
      }
      const workspace = createEmptyWorkspace();
      workspace.requirementText = localRequirementText;
      workspace.rules = [...localRequirementRules];
      workspace.requirementBaseline = localRequirementBaseline;
      workspace.requirementQualityReport =
        localRequirementBaseline?.qualityReport ?? null;
      workspace.requirementReviewCandidates = {
        ...localRequirementReviewCandidates,
      };
      workspace.autoGeneratedUpstreamReviews = {
        ...localAutoGeneratedUpstreamReviews,
      };
      workspace.requirementInputFingerprint = localRequirementInputFingerprint;
      workspace.rulesVersion = localRulesVersion;
      workspace.rulesBasedOnTextVersion = localRulesBasedOnTextVersion;
      return workspace;
    },

    async updateRequirementText(text: string) {
      if (projectId) {
        await updateProjectWorkspace((workspace) => {
          workspace.requirementText = text;
        });
        return;
      }
      localRequirementText = text;
    },

    async updateRequirementRules(
      rules: RequirementRule[],
      metadata?: RequirementRulesUpdateMetadata,
    ) {
      if (projectId) {
        await updateProjectWorkspace((workspace) => {
          workspace.rules = [...rules];
          if ("requirementInputFingerprint" in (metadata ?? {})) {
            workspace.requirementInputFingerprint =
              metadata?.requirementInputFingerprint ?? null;
          }
          if ("rulesBasedOnTextVersion" in (metadata ?? {})) {
            workspace.rulesBasedOnTextVersion =
              metadata?.rulesBasedOnTextVersion ?? null;
          }
          if (typeof metadata?.rulesVersion === "number") {
            workspace.rulesVersion = metadata.rulesVersion;
          }
        });
        return;
      }
      localRequirementRules = [...rules];
      if ("requirementInputFingerprint" in (metadata ?? {})) {
        localRequirementInputFingerprint =
          metadata?.requirementInputFingerprint ?? null;
      }
      if ("rulesBasedOnTextVersion" in (metadata ?? {})) {
        localRulesBasedOnTextVersion = metadata?.rulesBasedOnTextVersion ?? null;
      }
      if (typeof metadata?.rulesVersion === "number") {
        localRulesVersion = metadata.rulesVersion;
      }
    },

    async updateRequirementBaseline(baseline: RequirementBaseline) {
      if (projectId) {
        await updateProjectWorkspace((workspace) => {
          workspace.requirementBaseline = baseline;
          workspace.requirementQualityReport = baseline.qualityReport;
        });
        return;
      }
      localRequirementBaseline = structuredClone(
        baseline,
      ) as RequirementBaseline;
    },

    async updateRequirementReviewCandidates(candidates) {
      if (projectId) {
        await updateProjectWorkspace((workspace) => {
          workspace.requirementReviewCandidates = structuredClone(
            candidates,
          ) as WorkspaceRecord["requirementReviewCandidates"];
        });
        return;
      }
      localRequirementReviewCandidates = structuredClone(
        candidates,
      ) as WorkspaceRecord["requirementReviewCandidates"];
    },

    async updateAutoGeneratedUpstreamReviews(reviews) {
      if (projectId) {
        await updateProjectWorkspace((workspace) => {
          workspace.autoGeneratedUpstreamReviews = structuredClone(
            reviews,
          ) as WorkspaceRecord["autoGeneratedUpstreamReviews"];
        });
        return;
      }
      localAutoGeneratedUpstreamReviews = structuredClone(
        reviews,
      ) as WorkspaceRecord["autoGeneratedUpstreamReviews"];
    },

    async updateRequirementReviewState(baseline, candidates) {
      if (projectId) {
        await updateProjectWorkspace((workspace) => {
          workspace.requirementBaseline = structuredClone(
            baseline,
          ) as RequirementBaseline;
          workspace.requirementQualityReport = baseline.qualityReport;
          workspace.requirementReviewCandidates = structuredClone(
            candidates,
          ) as WorkspaceRecord["requirementReviewCandidates"];
        });
        return;
      }
      localRequirementBaseline = structuredClone(
        baseline,
      ) as RequirementBaseline;
      localRequirementReviewCandidates = structuredClone(
        candidates,
      ) as WorkspaceRecord["requirementReviewCandidates"];
    },

    async repairRequirementRule(input: RepairRequirementRuleRequest) {
      return repairRequirementRuleRequest(input, projectId);
    },

    async repairRequirementRules(input: RepairRequirementRulesRequest) {
      return repairRequirementRulesRequest(input, projectId);
    },

    async startRun(input: StartRunInput) {
      await waitForProjectWorkspaceSaves();
      return startRequirementRunRequest(input, projectId);
    },

    async startDesignRun(input: StartDesignRunInput) {
      await waitForProjectWorkspaceSaves();
      return startDesignRunRequest(input, projectId);
    },

    async startCodeRun(input: StartCodeRunInput) {
      await waitForProjectWorkspaceSaves();
      return startCodeRunRequest(input, projectId);
    },

    async startDocumentRun(input: StartDocumentRunInput) {
      await waitForProjectWorkspaceSaves();
      return startDocumentRunRequest(input, projectId);
    },

    async subscribeToRun(runId: string, onEvent: (event: RunEvent) => void) {
      await subscribeToRequirementRunEvents({
        runId,
        projectId,
        onEvent,
      });
    },

    async subscribeToDesignRun(
      runId: string,
      onEvent: (event: RunEvent) => void,
    ) {
      await subscribeToDesignRunEvents({ runId, projectId, onEvent });
    },

    async subscribeToCodeRun(
      runId: string,
      onEvent: (event: RunEvent) => void,
    ) {
      await subscribeToCodeRunEvents({ runId, projectId, onEvent });
    },

    async subscribeToDocumentRun(
      runId: string,
      onEvent: (event: RunEvent) => void,
    ) {
      await subscribeToDocumentRunEvents({ runId, projectId, onEvent });
    },

    async getRunSnapshot(runId: string) {
      return readRunSnapshot(runId, requireProjectScope(projectId));
    },

    async getDesignRunSnapshot(runId: string) {
      return readDesignRunSnapshot(runId, requireProjectScope(projectId));
    },

    async getCodeRunSnapshot(runId: string) {
      return readCodeRunSnapshot(runId, requireProjectScope(projectId));
    },

    async getDocumentRunSnapshot(runId: string) {
      return readDocumentRunSnapshot(runId, requireProjectScope(projectId));
    },

    async getRunEvidence(runId: string) {
      return readRunEvidencePackage(runId, requireProjectScope(projectId));
    },

    async submitRunReviewDecision(runId, decision) {
      return postRunReviewDecision(
        runId,
        decision,
        requireProjectScope(projectId),
      );
    },

    async listDocuments() {
      return listDocumentLibraryItems(projectId);
    },

    async getOnlyOfficeEditorConfig(
      documentId: string,
      uiTheme?: OnlyOfficeUiTheme,
    ) {
      return readOnlyOfficeEditorConfig(documentId, uiTheme, projectId);
    },

    async downloadDocumentRun(runId: string, defaultFileName?: string) {
      return downloadDocumentRunFile(runId, defaultFileName, projectId);
    },

    async downloadDocument(documentId: string, defaultFileName?: string) {
      return downloadDocumentFile(documentId, defaultFileName, projectId);
    },

    async renderPlantUml(diagramKind, plantUmlSource) {
      return renderPlantUmlRequest(diagramKind, plantUmlSource, projectId);
    },

    async renderStructuredModel(model) {
      return renderStructuredModelRequest(model, projectId);
    },

    async saveRequirementModelEdit(_diagramKind, model, status) {
      const workspace = await ensureProjectWorkspace();
      const modelKey = getRequirementModelId(model);
      workspace.models = { ...workspace.models, [modelKey]: model };
      workspace.manualModelEditStatus = {
        ...workspace.manualModelEditStatus,
        [modelKey]: status,
      };
      await saveProjectWorkspace(workspace);
    },

    async saveDesignModelEdit(modelId, model, status) {
      const workspace = await ensureProjectWorkspace();
      workspace.designModels = { ...workspace.designModels, [modelId]: model };
      workspace.manualModelEditStatus = {
        ...workspace.manualModelEditStatus,
        [modelId]: status,
      };
      await saveProjectWorkspace(workspace);
    },

    async saveManualModelRerender(key, status, artifact) {
      const workspace = await ensureProjectWorkspace();
      workspace.manualModelEditStatus = {
        ...workspace.manualModelEditStatus,
        [key]: status,
      };
      if (key in workspace.designModels) {
        workspace.designPlantUml = {
          ...workspace.designPlantUml,
          [key]: artifact.plantUmlSource,
        };
        workspace.designSvgArtifacts = {
          ...workspace.designSvgArtifacts,
          [key]: artifact.svgArtifact as DesignSvgArtifact,
        };
      } else {
        const diagramKind = key as DiagramType;
        workspace.plantUml = {
          ...workspace.plantUml,
          [diagramKind]: artifact.plantUmlSource,
        };
        workspace.svgArtifacts = {
          ...workspace.svgArtifacts,
          [diagramKind]: artifact.svgArtifact as SvgArtifact,
        };
      }
      await saveProjectWorkspace(workspace);
    },

    async testProviderSettings(providerSettings) {
      return testProviderSettingsRequest(providerSettings);
    },

    async saveRunHistory(snapshot, meta) {
      if (projectId) {
        await persistSnapshotAsProjectWorkspace(snapshot);
        return {
          id: snapshot.runId,
          createdAt: new Date().toISOString(),
          title: createRunHistoryTitle(snapshot.requirementText),
          snapshot,
          providerModel: meta.providerModel,
          durationMs: meta.durationMs,
        };
      }
      throw new Error(PROJECT_REQUIRED_MESSAGE);
    },

    async listRunHistory() {
      if (projectId) {
        const payload = await readProjectRuns();
        return normalizeProjectHistoryResponse(payload);
      }
      throw new Error(PROJECT_REQUIRED_MESSAGE);
    },

    async getRunHistoryItem(id) {
      if (projectId) {
        return readProjectRunHistoryItem(id);
      }
      return loadRunHistory().find((item) => item.id === id) ?? null;
    },

    async restoreRunHistory(id) {
      if (projectId) {
        await restoreProjectWorkspaceFromRun(id);
        return projectRunSummaryToHistoryItem({
          runId: id,
          status: "completed",
          snapshotAvailable: true,
          canRestore: true,
        });
      }
      throw new Error(PROJECT_REQUIRED_MESSAGE);
    },

    async deleteRunHistory(id) {
      if (projectId) {
        await requestJson(
          `/api/projects/${encodeURIComponent(projectId)}/runs/${encodeURIComponent(id)}`,
          withProjectHeaders(projectId, {
            method: "DELETE",
            errorMessage: "删除项目运行历史失败",
          }),
        );
        const history = await readProjectRuns();
        return normalizeProjectHistoryResponse(history);
      }
      throw new Error(PROJECT_REQUIRED_MESSAGE);
    },

    async clearRunHistory() {
      if (projectId) {
        await requestJson(
          `/api/projects/${encodeURIComponent(projectId)}/runs`,
          withProjectHeaders(projectId, {
            method: "DELETE",
            errorMessage: "清空项目运行历史失败",
          }),
        );
        return;
      }
      throw new Error(PROJECT_REQUIRED_MESSAGE);
    },
  };
}
