// Hosts the in-memory workspace repository used by tests and local flows without touching the HTTP adapter.
import {
  designRecordBelongsToDiagramKinds,
  designTraceabilityTouchesDiagramKinds,
  type CodeRunSnapshot,
  type DesignRunSnapshot,
  type DesignSvgArtifact,
  type DocumentLibraryItem,
  type DocumentRunSnapshot,
  type RequirementBaseline,
  type RunSnapshot,
  type SvgArtifact,
} from "@uml-platform/contracts";
import {
  getRequirementModelId,
  type DesignDiagramType,
  type DiagramType,
} from "../../entities/diagram/model";
import type { WorkspaceRecord } from "../../entities/workspace/model";
import type { RequirementRule } from "../../entities/requirement-rule/model";
import {
  clearRunHistoryItems,
  deleteRunHistoryItem,
  loadRunHistory,
  saveRunHistoryItem,
} from "../../entities/run-history";
import { documentFileName } from "./document-api";
import type {
  StartCodeRunInput,
  StartDesignRunInput,
  StartDocumentRunInput,
  StartRunInput,
} from "./start-inputs";
import {
  applySnapshotToWorkspace,
  createEmptyWorkspace,
} from "./workspace-state";
import type { WorkspaceRepository } from "./types";

export function createMockWorkspaceRepository(
  seed: Partial<WorkspaceRecord> = {},
  snapshotFactory?: (input: StartRunInput, runId: string) => RunSnapshot,
): WorkspaceRepository {
  const defaultWorkspace = createEmptyWorkspace();
  let workspace: WorkspaceRecord = {
    ...defaultWorkspace,
    ...seed,
    models: { ...defaultWorkspace.models, ...seed.models },
    requirementModelTraceability: seed.requirementModelTraceability
      ? [...seed.requirementModelTraceability]
      : [],
    plantUml: { ...defaultWorkspace.plantUml, ...seed.plantUml },
    svgArtifacts: { ...defaultWorkspace.svgArtifacts, ...seed.svgArtifacts },
    requirementInputFingerprint:
      seed.requirementInputFingerprint ??
      defaultWorkspace.requirementInputFingerprint,
    requirementReviewCandidates: {
      ...defaultWorkspace.requirementReviewCandidates,
      ...seed.requirementReviewCandidates,
    },
    autoGeneratedUpstreamReviews: {
      ...defaultWorkspace.autoGeneratedUpstreamReviews,
      ...seed.autoGeneratedUpstreamReviews,
    },
    diagramInputFingerprints: {
      ...defaultWorkspace.diagramInputFingerprints,
      ...seed.diagramInputFingerprints,
    },
    diagramVersions: {
      ...defaultWorkspace.diagramVersions,
      ...seed.diagramVersions,
    },
    designModels: { ...defaultWorkspace.designModels, ...seed.designModels },
    designModelTraceability: seed.designModelTraceability
      ? [...seed.designModelTraceability]
      : [],
    designPlantUml: {
      ...defaultWorkspace.designPlantUml,
      ...seed.designPlantUml,
    },
    designSvgArtifacts: {
      ...defaultWorkspace.designSvgArtifacts,
      ...seed.designSvgArtifacts,
    },
    designInputFingerprints: {
      ...defaultWorkspace.designInputFingerprints,
      ...seed.designInputFingerprints,
    },
    rules: seed.rules ? [...seed.rules] : [],
    selectedDiagramTypes: seed.selectedDiagramTypes
      ? [...seed.selectedDiagramTypes]
      : [],
    generatedDiagramTypes: seed.generatedDiagramTypes
      ? [...seed.generatedDiagramTypes]
      : [],
    diagramErrors: { ...defaultWorkspace.diagramErrors, ...seed.diagramErrors },
    selectedDesignDiagramTypes: seed.selectedDesignDiagramTypes
      ? [...seed.selectedDesignDiagramTypes]
      : [],
    generatedDesignDiagramTypes: seed.generatedDesignDiagramTypes
      ? [...seed.generatedDesignDiagramTypes]
      : [],
    designDiagramErrors: {
      ...defaultWorkspace.designDiagramErrors,
      ...seed.designDiagramErrors,
    },
    manualModelEditStatus: {
      ...defaultWorkspace.manualModelEditStatus,
      ...seed.manualModelEditStatus,
    },
    codeFiles: { ...defaultWorkspace.codeFiles, ...seed.codeFiles },
    codeDependencies: {
      ...defaultWorkspace.codeDependencies,
      ...seed.codeDependencies,
    },
    codeUiMockup: seed.codeUiMockup ?? null,
  };
  const snapshots = new Map<string, RunSnapshot>();
  const designSnapshots = new Map<string, DesignRunSnapshot>();
  const codeSnapshots = new Map<string, CodeRunSnapshot>();
  const documentSnapshots = new Map<string, DocumentRunSnapshot>();
  const documentBuffers = new Map<string, Blob>();
  const documents = new Map<string, DocumentLibraryItem>();

  return {
    async loadWorkspace() {
      return {
        ...workspace,
        rules: [...workspace.rules],
        selectedDiagramTypes: [...workspace.selectedDiagramTypes],
        generatedDiagramTypes: [...workspace.generatedDiagramTypes],
        models: { ...workspace.models },
        requirementModelTraceability: [
          ...workspace.requirementModelTraceability,
        ],
        plantUml: { ...workspace.plantUml },
        svgArtifacts: { ...workspace.svgArtifacts },
        diagramErrors: { ...workspace.diagramErrors },
        selectedDesignDiagramTypes: [...workspace.selectedDesignDiagramTypes],
        generatedDesignDiagramTypes: [...workspace.generatedDesignDiagramTypes],
        designModels: { ...workspace.designModels },
        designModelTraceability: [...workspace.designModelTraceability],
        designPlantUml: { ...workspace.designPlantUml },
        designSvgArtifacts: { ...workspace.designSvgArtifacts },
        designDiagramErrors: { ...workspace.designDiagramErrors },
        manualModelEditStatus: { ...workspace.manualModelEditStatus },
        codeSpec: workspace.codeSpec,
        codeBusinessLogic: workspace.codeBusinessLogic,
        codeFiles: { ...workspace.codeFiles },
        codeEntryFile: workspace.codeEntryFile,
        codeDependencies: { ...workspace.codeDependencies },
        codeUiMockup: workspace.codeUiMockup,
        codeAgentPlan: [...workspace.codeAgentPlan],
        codeSkills: [...workspace.codeSkills],
        codeSkillDiagnostics: [...workspace.codeSkillDiagnostics],
        codeSkillResourcePlan: workspace.codeSkillResourcePlan,
        codeSkillContext: workspace.codeSkillContext,
        codeDiagnostics: [...workspace.codeDiagnostics],
        requirementReviewCandidates: {
          ...workspace.requirementReviewCandidates,
        },
        requirementInputFingerprint: workspace.requirementInputFingerprint,
        diagramInputFingerprints: { ...workspace.diagramInputFingerprints },
        designInputFingerprints: { ...workspace.designInputFingerprints },
        rulesVersion: workspace.rulesVersion,
        rulesBasedOnTextVersion: workspace.rulesBasedOnTextVersion,
        diagramVersions: { ...workspace.diagramVersions },
      };
    },

    async updateRequirementText(text: string) {
      workspace = {
        ...workspace,
        requirementText: text,
      };
    },

    async updateRequirementRules(rules: RequirementRule[]) {
      workspace = {
        ...workspace,
        rules: [...rules],
      };
    },

    async updateRequirementBaseline(baseline: RequirementBaseline) {
      const nextBaseline = structuredClone(baseline) as RequirementBaseline;
      workspace = {
        ...workspace,
        requirementBaseline: nextBaseline,
        requirementQualityReport: nextBaseline.qualityReport,
      };
    },

    async updateRequirementReviewCandidates(candidates) {
      workspace = {
        ...workspace,
        requirementReviewCandidates: structuredClone(
          candidates,
        ) as WorkspaceRecord["requirementReviewCandidates"],
      };
    },

    async updateAutoGeneratedUpstreamReviews(reviews) {
      workspace = {
        ...workspace,
        autoGeneratedUpstreamReviews: structuredClone(
          reviews,
        ) as WorkspaceRecord["autoGeneratedUpstreamReviews"],
      };
    },

    async updateRequirementReviewState(baseline, candidates) {
      const nextBaseline = structuredClone(baseline) as RequirementBaseline;
      workspace = {
        ...workspace,
        requirementBaseline: nextBaseline,
        requirementQualityReport: nextBaseline.qualityReport,
        requirementReviewCandidates: structuredClone(
          candidates,
        ) as WorkspaceRecord["requirementReviewCandidates"],
      };
    },

    async repairRequirementRule() {
      throw new Error("当前环境不支持单项智能修复");
    },

    async repairRequirementRules() {
      throw new Error("当前环境不支持批量智能修复");
    },

    async startRun(input: StartRunInput) {
      const runId = `run-${Math.random().toString(36).slice(2, 10)}`;
      const snapshot = snapshotFactory?.(input, runId) ?? {
        runId,
        requirementText: input.requirementText,
        selectedDiagrams: input.selectedDiagrams,
        rules:
          input.rules.length > 0
            ? input.rules
            : (workspace.rules as RequirementRule[]),
        models: Object.values(workspace.models),
        requirementModelTraceability: [
          ...workspace.requirementModelTraceability,
        ],
        plantUml: Object.entries(workspace.plantUml).map(
          ([diagramKind, source]) => ({
            diagramKind: diagramKind as DiagramType,
            source,
          }),
        ),
        svgArtifacts: Object.values(workspace.svgArtifacts),
        diagramErrors: workspace.diagramErrors,
        requirementTrace: [],
        currentStage: "render_svg",
        status: "completed",
        error: null,
      };
      snapshots.set(runId, snapshot);
      return { runId };
    },

    async startDesignRun(input: StartDesignRunInput) {
      const runId = `design-run-${Math.random().toString(36).slice(2, 10)}`;
      const replacingDiagrams = Array.from(
        new Set([
          ...input.selectedDiagrams,
          ...(input.requestedDiagrams ?? []),
        ]),
      );
      const existingDesignModels = Object.entries(workspace.designModels)
        .filter(
          ([modelId, model]) =>
            !designRecordBelongsToDiagramKinds(
              modelId,
              model,
              replacingDiagrams,
            ),
        )
        .map(([, model]) => model);
      const existingDesignPlantUml = Object.entries(workspace.designPlantUml)
        .filter(
          ([artifactId, source]) =>
            !designRecordBelongsToDiagramKinds(
              artifactId,
              { modelId: artifactId, source },
              replacingDiagrams,
            ),
        )
        .map(([artifactId, source]) => {
          const model = workspace.designModels[artifactId];
          const svgArtifact = workspace.designSvgArtifacts[artifactId];
          const diagramKind =
            model?.diagramKind ??
            svgArtifact?.diagramKind ??
            (artifactId as DesignDiagramType);
          return {
            diagramKind,
            modelId: model?.modelId ?? svgArtifact?.modelId,
            source,
          };
        });
      const snapshot: DesignRunSnapshot = {
        runId,
        requirementText: "",
        selectedDiagrams: input.selectedDiagrams,
        requestedDiagrams: input.requestedDiagrams,
        rules: [],
        requirementBaseline: input.requirementBaseline,
        requirementModels: input.requirementModels,
        requirementModelTraceability: input.requirementModelTraceability,
        models: existingDesignModels,
        designModelTraceability: workspace.designModelTraceability.filter(
          (entry) =>
            !designTraceabilityTouchesDiagramKinds(entry, replacingDiagrams),
        ),
        plantUml: existingDesignPlantUml,
        svgArtifacts: Object.entries(workspace.designSvgArtifacts)
          .filter(
            ([artifactId, artifact]) =>
              !designRecordBelongsToDiagramKinds(
                artifactId,
                artifact,
                replacingDiagrams,
              ),
          )
          .map(([, artifact]) => artifact),
        diagramErrors: workspace.designDiagramErrors,
        designTrace: [],
        currentStage: "render_svg",
        status: "completed",
        error: null,
      };
      designSnapshots.set(runId, snapshot);
      return { runId };
    },

    async startCodeRun(input: StartCodeRunInput) {
      const runId = `code-run-${Math.random().toString(36).slice(2, 10)}`;
      const mergedFiles =
        input.generationMode === "regenerate"
          ? {
              "/src/App.tsx":
                workspace.codeFiles["/src/App.tsx"] ??
                "export default function App() { return <main>重新生成的原型</main>; }",
            }
          : {
              ...workspace.codeFiles,
              ...input.existingFiles,
            };
      const snapshot: CodeRunSnapshot = {
        runId,
        requirementText: input.requirementText,
        rules: input.rules,
        designModels: input.designModels,
        designPlantUml: input.designPlantUml,
        spec: workspace.codeSpec,
        loadedCodeSkill: null,
        skillResourcePlan: null,
        codeSkillContext: null,
        appBlueprint: workspace.codeSpec?.appBlueprint ?? null,
        businessLogic: workspace.codeBusinessLogic,
        uiBlueprint: workspace.codeSpec?.uiBlueprint ?? null,
        uiMockup: null,
        uiReferenceSpec: null,
        uiFidelityReport: null,
        designTokens: null,
        componentRegistry: null,
        uiIr: null,
        visualDiffReport: null,
        repairLoopSummary: null,
        selectedCodeSkills: [],
        skillDiagnostics: [],
        filePlan: workspace.codeSpec?.filePlan ?? null,
        codeImplementationBrief: null,
        codeFileOperationManifest: null,
        fileGenerationDiagnostics: [],
        codeTrace: [],
        codeGenerationMode: "json_schema_operations",
        qualityDiagnostics: [],
        files: mergedFiles,
        entryFile: workspace.codeEntryFile,
        dependencies: workspace.codeDependencies,
        agentPlan: ["写入骨架", "生成核心界面", "检查预览入口"],
        generationMode: input.generationMode,
        changedFileCount: 0,
        diagnostics: [],
        codeContextHash: "mock",
        currentStage: "write_code_files",
        status: "completed",
        error: null,
      };
      codeSnapshots.set(runId, snapshot);
      return { runId };
    },

    async startDocumentRun(input: StartDocumentRunInput) {
      const runId = `document-run-${Math.random().toString(36).slice(2, 10)}`;
      const fileName = documentFileName(input.documentKind);
      const documentId = `doc-${input.documentKind}-${Math.random().toString(36).slice(2, 10)}`;
      const snapshot: DocumentRunSnapshot = {
        runId,
        documentKind: input.documentKind,
        requirementText: input.requirementText,
        documentId,
        sections: [
          { level: 1, title: "1 引言", body: ["Mock 说明书正文。"] },
          {
            level: 2,
            title: "1.1 编写目的",
            body: ["用于验证说明书生成流程。"],
          },
          { level: 3, title: "1.1.1 范围", body: ["当前为 Mock 快照。"] },
        ],
        fileName,
        mimeType:
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        byteLength: 12,
        missingArtifacts: [],
        currentStage: "render_document_file",
        status: "completed",
        error: null,
      };
      const now = new Date().toISOString();
      documents.set(documentId, {
        id: documentId,
        workspaceId: "mock-workspace",
        documentKind: input.documentKind,
        title:
          input.documentKind === "requirementsSpec"
            ? "需求规格说明书"
            : "软件设计说明书",
        fileName,
        mimeType: snapshot.mimeType ?? "application/octet-stream",
        byteLength: snapshot.byteLength,
        version: 1,
        sourceRunId: runId,
        createdAt: now,
        updatedAt: now,
      });
      documentSnapshots.set(runId, snapshot);
      documentBuffers.set(
        runId,
        new Blob(["mock document"], {
          type: snapshot.mimeType ?? "application/octet-stream",
        }),
      );
      return { runId };
    },

    async subscribeToRun(runId, onEvent) {
      const snapshot = snapshots.get(runId);
      if (!snapshot) {
        throw new Error("Mock run not found");
      }
      onEvent({ type: "queued" });
      if (snapshot.rules.length > 0) {
        onEvent({
          type: "stage_started",
          stage: "extract_rules",
        });
      }
      onEvent({ type: "completed", snapshot });
    },

    async subscribeToCodeRun(runId, onEvent) {
      const snapshot = codeSnapshots.get(runId);
      if (!snapshot) {
        throw new Error("Mock code run not found");
      }
      onEvent({ type: "queued" });
      onEvent({
        type: "stage_started",
        stage: "plan_code",
      });
      onEvent({
        type: "stage_started",
        stage: "write_code_files",
      });
      onEvent({
        type: "code_file_changed",
        path: "/src/App.tsx",
        content:
          snapshot.files["/src/App.tsx"] ??
          "export default function App() { return null; }",
        reason: "Mock 生成器写入入口组件",
      });
      onEvent({ type: "completed", snapshot });
    },

    async subscribeToDocumentRun(runId, onEvent) {
      const snapshot = documentSnapshots.get(runId);
      if (!snapshot) {
        throw new Error("Mock document run not found");
      }
      onEvent({ type: "queued" });
      onEvent({ type: "stage_started", stage: "generate_document_text" });
      onEvent({
        type: "stage_progress",
        stage: "generate_document_text",
        progress: 55,
        message: "正在生成说明书正文",
      });
      onEvent({ type: "stage_started", stage: "render_document_file" });
      onEvent({
        type: "artifact_ready",
        stage: "render_document_file",
        artifactKind: "document",
      });
      onEvent({ type: "completed", snapshot });
    },

    async subscribeToDesignRun(runId, onEvent) {
      const snapshot = designSnapshots.get(runId);
      if (!snapshot) {
        throw new Error("Mock design run not found");
      }
      onEvent({ type: "queued" });
      onEvent({
        type: "stage_started",
        stage: "generate_design_sequence",
      });
      onEvent({ type: "completed", snapshot });
    },

    async getRunSnapshot(runId) {
      const snapshot = snapshots.get(runId);
      if (!snapshot) {
        throw new Error("Mock run not found");
      }
      workspace = applySnapshotToWorkspace(workspace, snapshot);
      return snapshot;
    },

    async getDesignRunSnapshot(runId) {
      const snapshot = designSnapshots.get(runId);
      if (!snapshot) {
        throw new Error("Mock design run not found");
      }
      workspace = applySnapshotToWorkspace(workspace, snapshot);
      return snapshot;
    },

    async getCodeRunSnapshot(runId) {
      const snapshot = codeSnapshots.get(runId);
      if (!snapshot) {
        throw new Error("Mock code run not found");
      }
      workspace = {
        ...workspace,
        codeSpec: snapshot.spec,
        codeFiles: { ...snapshot.files },
        codeEntryFile: snapshot.entryFile,
        codeDependencies: { ...snapshot.dependencies },
        codeUiMockup: snapshot.uiMockup,
        codeAgentPlan: [...snapshot.agentPlan],
        codeSkills: [...snapshot.selectedCodeSkills],
        codeSkillDiagnostics: [...snapshot.skillDiagnostics],
        codeSkillResourcePlan: snapshot.skillResourcePlan,
        codeSkillContext: snapshot.codeSkillContext,
        codeDiagnostics: [...snapshot.diagnostics],
      };
      return snapshot;
    },

    async getDocumentRunSnapshot(runId) {
      const snapshot = documentSnapshots.get(runId);
      if (!snapshot) {
        throw new Error("Mock document run not found");
      }
      return snapshot;
    },

    async getRunEvidence(runId) {
      const snapshot =
        snapshots.get(runId) ??
        designSnapshots.get(runId) ??
        codeSnapshots.get(runId) ??
        documentSnapshots.get(runId);
      if (!snapshot?.evidencePackage) {
        throw new Error("Mock evidence package not found");
      }
      return snapshot.evidencePackage;
    },

    async submitRunReviewDecision(runId, decision) {
      const snapshot =
        snapshots.get(runId) ??
        designSnapshots.get(runId) ??
        codeSnapshots.get(runId) ??
        documentSnapshots.get(runId);
      if (!snapshot?.evidencePackage) {
        throw new Error("Mock evidence package not found");
      }
      const resolved = {
        ...snapshot.evidencePackage,
        status: "complete" as const,
        reviewItems: snapshot.evidencePackage.reviewItems.map((item) =>
          item.id === decision.reviewItemId
            ? {
                ...item,
                status: "resolved" as const,
                decision: {
                  id: "DEC-MOCK",
                  reviewItemId: decision.reviewItemId,
                  decision: decision.decision,
                  comment: decision.comment,
                  decidedAt: new Date().toISOString(),
                },
              }
            : item,
        ),
        reviewDecisions: [
          ...snapshot.evidencePackage.reviewDecisions.filter(
            (item) => item.reviewItemId !== decision.reviewItemId,
          ),
          {
            id: "DEC-MOCK",
            reviewItemId: decision.reviewItemId,
            decision: decision.decision,
            comment: decision.comment,
            decidedAt: new Date().toISOString(),
          },
        ],
      };
      snapshot.evidencePackage = resolved;
      return resolved;
    },

    async listDocuments() {
      return Array.from(documents.values()).sort((left, right) =>
        right.updatedAt.localeCompare(left.updatedAt),
      );
    },

    async getOnlyOfficeEditorConfig(documentId, uiTheme = "theme-dark") {
      const document = documents.get(documentId);
      if (!document) {
        throw new Error("Mock document not found");
      }
      return {
        document,
        documentServerUrl: "http://127.0.0.1:8080",
        config: {
          documentType: "word",
          document: {
            fileType: "docx",
            key: `${document.id}-v${document.version}`,
            title: document.fileName,
            url: `/api/documents/${document.id}/file`,
          },
          editorConfig: {
            callbackUrl: `/api/documents/${document.id}/onlyoffice/callback`,
            mode: "edit",
            lang: "zh-CN",
            customization: {
              uiTheme,
            },
          },
        },
      };
    },

    async downloadDocumentRun(runId, defaultFileName) {
      const snapshot = documentSnapshots.get(runId);
      const blob = documentBuffers.get(runId);
      if (!snapshot || !blob) {
        throw new Error("Mock document file not found");
      }
      return {
        blob,
        fileName: snapshot.fileName ?? defaultFileName ?? "说明书.docx",
      };
    },

    async downloadDocument(documentId, defaultFileName) {
      const document = documents.get(documentId);
      const runId = document?.sourceRunId;
      const blob = runId ? documentBuffers.get(runId) : null;
      if (!document || !blob) {
        throw new Error("Mock document file not found");
      }
      return {
        blob,
        fileName: document.fileName ?? defaultFileName ?? "说明书.docx",
      };
    },

    async renderPlantUml(diagramKind, plantUmlSource) {
      return {
        svg: `<svg><text>${diagramKind}</text></svg>`,
        renderMeta: {
          engine: "plantuml",
          generatedAt: new Date().toISOString(),
          sourceLength: plantUmlSource.length,
          durationMs: 1,
        },
      };
    },

    async renderStructuredModel(model) {
      const source = `@startuml\n' ${model.title}\n@enduml`;
      return {
        plantUmlSource: source,
        svg: `<svg><text>${model.diagramKind}</text></svg>`,
        renderMeta: {
          engine: "plantuml",
          generatedAt: new Date().toISOString(),
          sourceLength: source.length,
          durationMs: 1,
        },
      };
    },

    async saveRequirementModelEdit(_diagramKind, model, status) {
      const modelKey = getRequirementModelId(model);
      workspace = {
        ...workspace,
        models: { ...workspace.models, [modelKey]: model },
        manualModelEditStatus: {
          ...workspace.manualModelEditStatus,
          [modelKey]: status,
        },
      };
    },

    async saveDesignModelEdit(modelId, model, status) {
      workspace = {
        ...workspace,
        designModels: { ...workspace.designModels, [modelId]: model },
        manualModelEditStatus: {
          ...workspace.manualModelEditStatus,
          [modelId]: status,
        },
      };
    },

    async saveManualModelRerender(key, status, artifact) {
      const isDesign = key in workspace.designModels;
      workspace = {
        ...workspace,
        manualModelEditStatus: {
          ...workspace.manualModelEditStatus,
          [key]: status,
        },
        ...(isDesign
          ? {
              designPlantUml: {
                ...workspace.designPlantUml,
                [key]: artifact.plantUmlSource,
              },
              designSvgArtifacts: {
                ...workspace.designSvgArtifacts,
                [key]: artifact.svgArtifact as DesignSvgArtifact,
              },
            }
          : {
              plantUml: {
                ...workspace.plantUml,
                [key as DiagramType]: artifact.plantUmlSource,
              },
              svgArtifacts: {
                ...workspace.svgArtifacts,
                [key as DiagramType]: artifact.svgArtifact as SvgArtifact,
              },
            }),
      };
    },

    async testProviderSettings() {
      return {
        ok: true,
        message: "Provider connection ok",
        capability: {
          supportsJsonSchema: true,
          modeLabel: "严格结构化",
        },
      };
    },

    async saveRunHistory(snapshot, meta) {
      return saveRunHistoryItem(snapshot, meta);
    },

    async listRunHistory() {
      return loadRunHistory();
    },

    async getRunHistoryItem(id) {
      return loadRunHistory().find((item) => item.id === id) ?? null;
    },

    async restoreRunHistory(id) {
      return loadRunHistory().find((item) => item.id === id) ?? null;
    },

    async deleteRunHistory(id) {
      return deleteRunHistoryItem(id);
    },

    async clearRunHistory() {
      clearRunHistoryItems();
    },
  };
}
