// Defines the workspace repository contract shared by HTTP, mock, and React provider adapters.
import type {
  CodeRunSnapshot,
  DesignDiagramModelSpec,
  DesignRunSnapshot,
  DesignSvgArtifact,
  DiagramModelSpec,
  DocumentLibraryItem,
  DocumentRunSnapshot,
  EvidencePackage,
  EvidenceReviewDecision,
  OnlyOfficeEditorConfigResponse,
  OnlyOfficeUiTheme,
  RenderStructuredModelResponse,
  RenderSvgResponse,
  RepairRequirementRuleRequest,
  RepairRequirementRuleResponse,
  RepairRequirementRulesRequest,
  RepairRequirementRulesResponse,
  RequirementBaseline,
  RunEvent,
  RunSnapshot,
  SvgArtifact,
} from "@uml-platform/contracts";
import type { DiagramType } from "../../entities/diagram/model";
import type {
  ManualModelEditStatus,
  WorkspaceRecord,
} from "../../entities/workspace/model";
import type { RequirementRule } from "../../entities/requirement-rule/model";
import type {
  RunHistoryItem,
  RunHistorySnapshot,
} from "../../entities/run-history";
import type { ModelCapability } from "../../shared/lib/model-catalog";
import type {
  ProviderSettingsInput,
  StartCodeRunInput,
  StartDesignRunInput,
  StartDocumentRunInput,
  StartRunInput,
} from "./start-inputs";

export interface WorkspaceRepository {
  loadWorkspace(): Promise<WorkspaceRecord>;
  getProjectCapabilities?(): Promise<string[]>;
  updateRequirementText(text: string): Promise<void>;
  updateRequirementRules?(rules: RequirementRule[]): Promise<void>;
  updateRequirementBaseline?(baseline: RequirementBaseline): Promise<void>;
  updateRequirementReviewCandidates?(
    candidates: WorkspaceRecord["requirementReviewCandidates"],
  ): Promise<void>;
  updateAutoGeneratedUpstreamReviews?(
    reviews: WorkspaceRecord["autoGeneratedUpstreamReviews"],
  ): Promise<void>;
  updateRequirementReviewState?(
    baseline: RequirementBaseline,
    candidates: WorkspaceRecord["requirementReviewCandidates"],
  ): Promise<void>;
  repairRequirementRule?(
    input: RepairRequirementRuleRequest,
  ): Promise<RepairRequirementRuleResponse>;
  repairRequirementRules?(
    input: RepairRequirementRulesRequest,
  ): Promise<RepairRequirementRulesResponse>;
  startRun(input: StartRunInput): Promise<{ runId: string }>;
  startDesignRun?(input: StartDesignRunInput): Promise<{ runId: string }>;
  startCodeRun?(input: StartCodeRunInput): Promise<{ runId: string }>;
  startDocumentRun?(input: StartDocumentRunInput): Promise<{ runId: string }>;
  subscribeToRun(
    runId: string,
    onEvent: (event: RunEvent) => void,
  ): Promise<void>;
  subscribeToDesignRun?(
    runId: string,
    onEvent: (event: RunEvent) => void,
  ): Promise<void>;
  subscribeToCodeRun?(
    runId: string,
    onEvent: (event: RunEvent) => void,
  ): Promise<void>;
  subscribeToDocumentRun?(
    runId: string,
    onEvent: (event: RunEvent) => void,
  ): Promise<void>;
  getRunSnapshot(runId: string): Promise<RunSnapshot>;
  getDesignRunSnapshot?(runId: string): Promise<DesignRunSnapshot>;
  getCodeRunSnapshot?(runId: string): Promise<CodeRunSnapshot>;
  getDocumentRunSnapshot?(runId: string): Promise<DocumentRunSnapshot>;
  getRunEvidence?(runId: string): Promise<EvidencePackage>;
  submitRunReviewDecision?(
    runId: string,
    decision: {
      reviewItemId: string;
      decision: EvidenceReviewDecision["decision"];
      comment: string;
    },
  ): Promise<EvidencePackage>;
  listDocuments?(): Promise<DocumentLibraryItem[]>;
  getOnlyOfficeEditorConfig?(
    documentId: string,
    uiTheme?: OnlyOfficeUiTheme,
  ): Promise<OnlyOfficeEditorConfigResponse>;
  downloadDocumentRun?(
    runId: string,
    defaultFileName?: string,
  ): Promise<{ blob: Blob; fileName: string }>;
  downloadDocument?(
    documentId: string,
    defaultFileName?: string,
  ): Promise<{ blob: Blob; fileName: string }>;
  renderPlantUml(
    diagramKind: DiagramType,
    plantUmlSource: string,
  ): Promise<RenderSvgResponse>;
  renderStructuredModel?(
    model: DiagramModelSpec | DesignDiagramModelSpec,
  ): Promise<RenderStructuredModelResponse>;
  saveRequirementModelEdit?(
    diagramKind: DiagramType,
    model: DiagramModelSpec,
    status: ManualModelEditStatus,
  ): Promise<void>;
  saveDesignModelEdit?(
    modelId: string,
    model: DesignDiagramModelSpec,
    status: ManualModelEditStatus,
  ): Promise<void>;
  saveManualModelRerender?(
    key: string,
    status: ManualModelEditStatus,
    artifact: {
      plantUmlSource: string;
      svgArtifact: SvgArtifact | DesignSvgArtifact;
    },
  ): Promise<void>;
  testProviderSettings(providerSettings: ProviderSettingsInput): Promise<{
    ok: boolean;
    message: string;
    capability: ModelCapability;
  }>;
  saveRunHistory(
    snapshot: RunHistorySnapshot,
    meta: { providerModel: string; durationMs?: number },
  ): Promise<RunHistoryItem>;
  listRunHistory(): Promise<RunHistoryItem[]>;
  getRunHistoryItem?(id: string): Promise<RunHistoryItem | null>;
  restoreRunHistory(id: string): Promise<RunHistoryItem | null>;
  deleteRunHistory(id: string): Promise<RunHistoryItem[]>;
  clearRunHistory(): Promise<void>;
}
