import { type MouseEvent, useEffect, useMemo, useRef, useState } from "react";
import {
  Wand2,
  Loader2,
  Search,
  AlertTriangle,
  RefreshCw,
  ArrowUp,
  Plus,
  Trash2,
  FileText,
  ListChecks,
  Network,
  Box,
  Server,
  GitBranch,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  Bot,
  SendHorizontal,
  ShoppingCart,
  MessageCircle,
  Activity,
  Eye,
  X,
} from "lucide-react";
import { Button } from "../../../shared/ui/button";
import { Badge } from "../../../shared/ui/badge";
import { Checkbox } from "../../../shared/ui/checkbox";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "../../../shared/ui/dialog";
import { Input } from "../../../shared/ui/input";
import { SelectControl } from "../../../shared/ui/select";
import { cn } from "../../../shared/ui/utils";
import type {
  AtomicRequirement,
  AtomicRequirementField,
  RequirementQualityIssue,
} from "@uml-platform/contracts";
import {
  DIAGRAM_META,
  DIAGRAM_ORDER,
  type DiagramType,
} from "../../../entities/diagram/model";
import {
  RULE_CATEGORY_ORDER,
  type RequirementRule,
} from "../../../entities/requirement-rule/model";
import type { WorkspaceRecord } from "../../../entities/workspace/model";
import { useWorkspaceSession } from "../../workspace-session/state";
import { ModelPicker } from "../../../shared/ui/model-picker";
import {
  loadUserSettings,
  patchUserSettings,
  USER_SETTINGS_CHANGED_EVENT,
} from "../../../shared/lib/user-settings";
import {
  MobileCompactGrid,
  MobileRail,
  MobileRailCard,
  mobileTouchTargetClass,
} from "../../workspace-shell/components/mobile-density";
import { ModelBentoCard } from "../../workspace-shell/components/model-bento-card";

const DEFAULT_NEW_RULE_DIAGRAMS: DiagramType[] = ["usecase", "activity"];
const RULES_PER_PAGE = 8;
const RULE_PAGE_SIZE_OPTIONS = [8, 12, 20, 50] as const;
const RULE_ROW_CLASS = "h-[60px]";
const ALL_RULE_CATEGORIES = "";
const REQUIREMENT_DIAGRAM_ICON = {
  usecase: Network,
  activity: Activity,
  class: Box,
  deployment: Server,
  prototype: Eye,
  analysis: GitBranch,
} satisfies Record<DiagramType, typeof Network>;
const REQUIREMENT_FIELD_LABELS: Record<AtomicRequirementField, string> = {
  actor: "角色/执行者",
  subject: "主体",
  action: "动作",
  object: "对象",
  condition: "条件",
  outcome: "结果",
  acceptanceCriteria: "验收标准",
};
const REVIEWABLE_REQUIREMENT_FIELDS = Object.keys(
  REQUIREMENT_FIELD_LABELS,
) as AtomicRequirementField[];
type AutoGeneratedUpstreamReview =
  WorkspaceRecord["autoGeneratedUpstreamReviews"][string];

function stageRepairCopy(text: string) {
  return text.replace(/\bAI\b\s*/gu, "系统");
}

function requirementHintCount(requirement: AtomicRequirement | undefined) {
  if (!requirement) return 0;
  return Object.values(requirement.fieldProvenance).filter(
    (item) => item?.source === "ai-suggested" || item?.status === "pending-review",
  ).length;
}

function requirementRowState(
  requirement: AtomicRequirement | undefined,
  qualityIssues: RequirementQualityIssue[] = [],
) {
  if (!requirement) return null;
  if (requirement.status === "conflict") return "存在冲突提示";
  const pendingAi = Object.values(requirement.fieldProvenance).some(
    (item) => item?.source === "ai-suggested" && item.status === "pending-review",
  );
  const rejectedOrManualPending = Object.values(requirement.fieldProvenance).some(
    (item) => item?.status === "rejected" || item?.status === "pending-review",
  );
  if (
    pendingAi ||
    rejectedOrManualPending ||
    qualityIssues.length > 0 ||
    requirement.status === "pending-review" ||
    requirement.status === "ambiguous"
  ) {
    return "有待确认提示";
  }
  const acceptedAi = Object.values(requirement.fieldProvenance).some(
    (item) => item?.source === "ai-suggested" && item.status === "accepted",
  );
  if (acceptedAi) return "已确认";
  return "已生成";
}

function requirementStateTone(state: string | null) {
  if (state === "已生成") return "border-success/40 bg-success/10 text-success";
  if (state === "已确认") return "border-success/40 bg-success/10 text-success";
  if (state === "有待确认提示") return "border-warning/40 bg-warning/10 text-warning";
  if (state === "存在冲突提示") return "border-destructive/40 bg-destructive/10 text-destructive";
  return "border-border bg-muted/40 text-muted-foreground";
}

function requirementFieldValue(
  requirement: AtomicRequirement,
  field: AtomicRequirementField,
) {
  const provenanceValue = requirement.fieldProvenance[field]?.value;
  if (typeof provenanceValue === "string" && provenanceValue.trim()) {
    return provenanceValue;
  }
  if (field === "acceptanceCriteria") {
    return requirement.acceptanceCriteria.join("；");
  }
  return requirement[field] ?? "";
}

function requirementFieldStatusLabel(status: string) {
  if (status === "accepted") return "已确认";
  if (status === "rejected") return "已拒绝";
  return "待确认";
}

function reviewCandidateStateLabel(
  candidate: WorkspaceRecord["requirementReviewCandidates"][string] | undefined,
  rowState: string | null,
) {
  if (candidate?.status === "failed") return "修复失败待重试";
  if (candidate?.status === "pending") return "修复结果待确认";
  if (candidate?.status === "accepted" || candidate?.status === "rejected") {
    return "已确认";
  }
  return rowState;
}

function reviewCandidateDecisionLabel(
  candidate: WorkspaceRecord["requirementReviewCandidates"][string] | undefined,
) {
  if (candidate?.status === "accepted") return "已采纳修复";
  if (candidate?.status === "rejected") return "已拒绝修复";
  return null;
}

function requirementSourceLabel(source: string) {
  if (source === "ai-suggested") return "AI补齐";
  if (source === "manual") return "手动编辑";
  if (source === "source-text") return "原文提取";
  return "规则推断";
}

function pendingAutoReviewsForRequirementDiagram(
  reviews: WorkspaceRecord["autoGeneratedUpstreamReviews"],
  diagram: DiagramType,
): AutoGeneratedUpstreamReview[] {
  return Object.values(reviews).filter(
    (review) =>
      review.status === "pending" &&
      ((review.artifactType === "requirement-model" &&
        review.artifactId === diagram) ||
        (review.artifactType === "requirement-rule" &&
          review.artifactId === `mapping:${diagram}`)),
  );
}

const REQUIREMENT_TEMPLATE_CARDS = [
  {
    title: "电商系统",
    english: "E-commerce System",
    description: "完善的购物流程与库存规则。",
    templateText:
      "我们需要开发一个电商系统。用户可以注册和登录账号，浏览商品、搜索商品、查看商品详情，将商品加入购物车并提交订单。系统需要支持订单支付、订单状态查询、收货地址管理和售后退款申请。管理员可以维护商品信息、管理库存、处理订单和查看销售统计。系统应保证未登录用户只能浏览公开商品，支付成功后才生成有效订单，并在库存不足时阻止下单。",
    Icon: ShoppingCart,
  },
  {
    title: "社交应用",
    english: "Social App",
    description: "用户交互与即时通讯逻辑。",
    templateText:
      "我们需要开发一个社交应用。用户可以注册账号、完善个人资料、发布动态、上传图片、关注其他用户并查看关注流。系统需要支持点赞、评论、私信聊天、消息通知和内容举报。管理员可以审核举报内容、管理违规用户和维护社区规则。系统应保证用户只能修改自己的资料和动态，私信只允许在合法用户之间发送，违规内容需要进入审核流程。",
    Icon: MessageCircle,
  },
  {
    title: "健身追踪",
    english: "Fitness Tracker",
    description: "健康数据可视化与目标追踪。",
    templateText:
      "我们需要开发一个健身追踪系统。用户可以记录每日运动、步数、体重、饮食和睡眠数据，设置健身目标并查看进度趋势。系统需要支持训练计划推荐、运动提醒、历史数据统计和健康报告生成。用户可以绑定可穿戴设备同步数据，也可以手动补录记录。系统应保证健康数据仅本人可见，设备同步失败时给出提示，并在用户达到阶段目标时发送通知。",
    Icon: Activity,
  },
] as const;

export function TextRequirementView() {
  const {
    requirementText,
    setRequirementText,
    rules,
    createRequirementRule,
    updateRequirementRule,
    deleteRequirementRule,
    selectedDiagrams,
    setSelectedDiagrams,
    generating,
    generateRules,
    generateDiagrams,
    isRulesStale,
    staleDiagrams,
    generatedDiagrams,
    requirementModelTraceability,
    autoGeneratedUpstreamReviews,
    decideAutoGeneratedUpstreamReview,
    requirementBaseline,
    requirementReviewCandidates,
    requirementReviewBlockedReason,
    repairRequirementRule,
    decideRequirementReviewCandidate,
    confirmRequirementQualityHint,
    canUpdateWorkspace,
    canStartRuns,
    workspacePermissionReason,
    billingGenerationBlock,
    clearBillingGenerationBlock,
  } = useWorkspaceSession();
  const [query, setQuery] = useState("");
  const [defaultModel, setDefaultModel] = useState(
    () => loadUserSettings().defaultModel,
  );
  const [showStaleBanner, setShowStaleBanner] = useState(
    () => loadUserSettings().showStaleBanner,
  );
  const [newRuleDialogOpen, setNewRuleDialogOpen] = useState(false);
  const [newRuleCategory, setNewRuleCategory] =
    useState<RequirementRule["category"]>("功能需求");
  const [newRuleDiagrams, setNewRuleDiagrams] = useState<DiagramType[]>(
    DEFAULT_NEW_RULE_DIAGRAMS,
  );
  const [newRuleText, setNewRuleText] = useState("");
  const [newRuleError, setNewRuleError] = useState<string | null>(null);
  const [modelRepairResult, setModelRepairResult] = useState<{
    targetLabel: string;
  } | null>(null);
  const [hintDetailRuleId, setHintDetailRuleId] = useState<string | null>(null);
  const [traceabilityDialogOpen, setTraceabilityDialogOpen] = useState(false);
  const [currentRulePage, setCurrentRulePage] = useState(1);
  const [rulePageSize, setRulePageSize] = useState(RULES_PER_PAGE);
  const [ruleCategoryFilter, setRuleCategoryFilter] = useState<
    RequirementRule["category"] | typeof ALL_RULE_CATEGORIES
  >(ALL_RULE_CATEGORIES);

  useEffect(() => {
    const syncSettings = () => {
      const settings = loadUserSettings();
      setDefaultModel(settings.defaultModel);
      setShowStaleBanner(settings.showStaleBanner);
    };

    window.addEventListener(USER_SETTINGS_CHANGED_EVENT, syncSettings);
    return () => {
      window.removeEventListener(USER_SETTINGS_CHANGED_EVENT, syncSettings);
    };
  }, []);

  const hasGeneratedRules = rules.length > 0;
  const hasRequirementSourceText = requirementText.trim().length > 0;
  const canEditRequirements = canUpdateWorkspace;
  const canRunGeneration = canUpdateWorkspace && canStartRuns;
  const editBlockedReason =
    workspacePermissionReason ?? "当前项目角色不能编辑需求内容。";
  const generationBlockedByPermissionReason =
    workspacePermissionReason ?? "当前项目角色不能启动生成。";

  const runGenerateRules = () => {
    if (!canRunGeneration) return;
    void generateRules();
  };

  const runGenerateDiagrams = (only?: DiagramType[]) => {
    if (!canRunGeneration) return;
    void generateDiagrams(only);
  };

  const decideAutoReviews = (
    event: MouseEvent<HTMLButtonElement>,
    reviews: AutoGeneratedUpstreamReview[],
    decision: "accepted" | "dismissed",
  ) => {
    event.stopPropagation();
    void Promise.all(
      reviews.map((review) =>
        decideAutoGeneratedUpstreamReview(review.id, decision),
      ),
    );
  };

  const updateModel = (model: string) => {
    if (!canRunGeneration) return;
    patchUserSettings({ defaultModel: model });
  };

  const selectableDiagramSet = useMemo(() => new Set(DIAGRAM_ORDER), []);

  const toggleDiagram = (diagram: DiagramType, checked: boolean) => {
    if (!canEditRequirements) return;
    if (checked && !selectableDiagramSet.has(diagram)) {
      return;
    }
    setSelectedDiagrams(
      checked
        ? Array.from(new Set([...selectedDiagrams, diagram]))
        : selectedDiagrams.filter((value) => value !== diagram),
    );
  };

  useEffect(() => {
    const nextSelectedDiagrams = selectedDiagrams.filter((diagram) =>
      selectableDiagramSet.has(diagram),
    );
    if (nextSelectedDiagrams.length !== selectedDiagrams.length) {
      setSelectedDiagrams(nextSelectedDiagrams);
    }
  }, [selectableDiagramSet, selectedDiagrams, setSelectedDiagrams]);

  const toggleNewRuleDiagram = (diagram: DiagramType, checked: boolean) => {
    setNewRuleDiagrams((current) =>
      checked
        ? Array.from(new Set([...current, diagram]))
        : current.filter((value) => value !== diagram),
    );
  };

  const resetNewRuleForm = () => {
    setNewRuleCategory("功能需求");
    setNewRuleDiagrams(DEFAULT_NEW_RULE_DIAGRAMS);
    setNewRuleText("");
    setNewRuleError(null);
  };

  const submitNewRule = () => {
    const trimmedText = newRuleText.trim();
    if (!trimmedText) {
      setNewRuleError("请填写需求文本。");
      return;
    }
    if (newRuleDiagrams.length === 0) {
      setNewRuleError("请至少选择一个对应模型。");
      return;
    }
    createRequirementRule({
      category: newRuleCategory,
      relatedDiagrams: newRuleDiagrams,
      text: trimmedText,
    });
    setNewRuleDialogOpen(false);
    resetNewRuleForm();
  };

  const newRuleCanSubmit = newRuleText.trim().length > 0 && newRuleDiagrams.length > 0;

  const filteredRules = useMemo(() => {
    const normalizedQuery = query.trim().toLowerCase();
    return rules.filter((rule) => {
      const matchesQuery =
        !normalizedQuery || rule.text.toLowerCase().includes(normalizedQuery);
      const matchesCategory =
        ruleCategoryFilter === ALL_RULE_CATEGORIES ||
        rule.category === ruleCategoryFilter;
      return matchesQuery && matchesCategory;
    });
  }, [rules, query, ruleCategoryFilter]);

  useEffect(() => {
    setCurrentRulePage(1);
  }, [query, ruleCategoryFilter]);

  const totalRulePages = Math.max(1, Math.ceil(filteredRules.length / rulePageSize));
  const safeRulePage = Math.min(currentRulePage, totalRulePages);
  const firstRuleIndex =
    filteredRules.length === 0 ? 0 : (safeRulePage - 1) * rulePageSize + 1;
  const lastRuleIndex = Math.min(filteredRules.length, safeRulePage * rulePageSize);
  const pagedRules = filteredRules.slice(firstRuleIndex - 1, lastRuleIndex);
  const emptyRuleSlots = Math.max(0, rulePageSize - pagedRules.length);
  const requirementByRuleId = useMemo(() => {
    const entries =
      requirementBaseline?.requirements
        .filter((requirement) => requirement.sourceRuleId)
        .map((requirement) => [requirement.sourceRuleId!, requirement] as const) ?? [];
    return new Map(entries);
  }, [requirementBaseline]);
  const qualityIssuesByRequirementId = useMemo(() => {
    const map = new Map<string, RequirementQualityIssue[]>();
    for (const issue of requirementBaseline?.qualityReport.issues ?? []) {
      if (!issue.requirementId) continue;
      map.set(issue.requirementId, [
        ...(map.get(issue.requirementId) ?? []),
        issue,
      ]);
    }
    return map;
  }, [requirementBaseline]);
  const hintDetail = useMemo(() => {
    if (!hintDetailRuleId) return null;
    const rule = rules.find((item) => item.id === hintDetailRuleId);
    const requirement = requirementByRuleId.get(hintDetailRuleId);
    if (!rule || !requirement) return null;
    const qualityIssues = qualityIssuesByRequirementId.get(requirement.id) ?? [];
    const fieldEntries = Object.entries(requirement.fieldProvenance).filter(
      (entry): entry is [
        AtomicRequirementField,
        NonNullable<AtomicRequirement["fieldProvenance"][AtomicRequirementField]>,
      ] => {
        const [, provenance] = entry;
        return Boolean(
          provenance &&
            (provenance.source === "ai-suggested" ||
              provenance.status === "pending-review" ||
              provenance.status === "rejected"),
        );
      },
    );
    return {
      rule,
      requirement,
      candidate: requirementReviewCandidates[hintDetailRuleId] ?? null,
      rowState: requirementRowState(requirement, qualityIssues),
      qualityIssues,
      fieldEntries,
    };
  }, [
    hintDetailRuleId,
    qualityIssuesByRequirementId,
    requirementByRuleId,
    requirementReviewCandidates,
    rules,
  ]);
  const lastHintDetailRef = useRef<typeof hintDetail>(null);
  if (hintDetail) {
    lastHintDetailRef.current = hintDetail;
  }
  const visibleHintDetail = hintDetail ?? lastHintDetailRef.current;
  useEffect(() => {
    if (currentRulePage > totalRulePages) {
      setCurrentRulePage(totalRulePages);
    }
  }, [currentRulePage, totalRulePages]);

  const generateDiagramsButtonLabel = (() => {
    const toAdd = selectedDiagrams.filter(
      (diagram) => !generatedDiagrams.includes(diagram),
    ).length;
    const toKeep = generatedDiagrams.filter(
      (diagram) => !selectedDiagrams.includes(diagram),
    ).length;
    const stale = staleDiagrams.filter((diagram) =>
      selectedDiagrams.includes(diagram),
    ).length;
    if (generatedDiagrams.length === 0) return "生成模型";
    const parts: string[] = [];
    if (toAdd) parts.push(`新增${toAdd}`);
    if (toKeep) parts.push(`保留${toKeep}`);
    if (stale) parts.push(`更新${stale}`);
    return parts.length ? `应用变更（${parts.join("·")}）` : "重新生成";
  })();
  const generationBlockedTitle =
    requirementReviewBlockedReason ?? undefined;
  const getRequirementTargetBlockReason = (diagram: DiagramType) => {
    if (isRulesStale && rules.length > 0) {
      return "需求规则已过期，请先更新需求规则";
    }
    if (rules.length === 0 && !hasRequirementSourceText) {
      const canGenerateAnalysisFromUseCase =
        diagram === "analysis" &&
        generatedDiagrams.includes("usecase");
      if (!canGenerateAnalysisFromUseCase) {
        return "请先输入需求描述或添加需求规则";
      }
    }
    if (
      diagram === "analysis" &&
      generatedDiagrams.includes("usecase") &&
      staleDiagrams.includes("usecase")
    ) {
      return "用例模型已存在但基于旧规则，请先更新用例模型";
    }
    return null;
  };
  const selectedTargetBlockReason =
    selectedDiagrams.map(getRequirementTargetBlockReason).find(Boolean) ?? null;
  const requirementModelRepairRecords = useMemo(() => {
    if (generatedDiagrams.length === 0 || requirementModelTraceability.length === 0) {
      return [];
    }
    return requirementModelTraceability.slice(0, 6).map((entry) => {
      const linkedRule = rules.find((rule) => rule.id === entry.ruleId);
      const targetDiagramLabel =
        entry.target.diagramKind in DIAGRAM_META
          ? DIAGRAM_META[entry.target.diagramKind as DiagramType].label
          : "需求模型";
      return {
        id: `${entry.ruleId}:${entry.target.diagramKind}:${entry.target.elementId}`,
        reason: linkedRule
          ? `需求规则 ${entry.ruleId} 需要解释其在${targetDiagramLabel}中的覆盖关系。`
          : `需求规则 ${entry.ruleId} 缺少可审查的模型覆盖解释。`,
        repair: `补齐 ${entry.ruleId} -> ${entry.target.label} 的追踪关系和覆盖说明`,
        targetLabel: `${targetDiagramLabel}：${entry.target.label}`,
        status: "证明已补齐",
      };
    });
  }, [generatedDiagrams.length, requirementModelTraceability, rules]);

  const renderRequirementInput = (mode: "empty" | "generated") => (
    <div
      className={cn(
        "relative",
        mode === "empty" &&
          "overflow-hidden rounded-xl border border-border bg-card p-6 shadow-sm",
      )}
    >
      {mode === "empty" && (
        <div className="absolute -right-20 -top-20 size-64 rounded-full bg-primary/5 blur-3xl" />
      )}
      <div className="relative flex items-center justify-between gap-4">
        <div className="flex items-center gap-2">
          <FileText className="size-5 text-primary" />
          <h2
            id="requirement-text-heading"
            className="text-xl font-semibold tracking-normal text-foreground"
          >
            {mode === "empty" ? "项目需求描述" : "需求描述"}
          </h2>
        </div>
      </div>
      <textarea
        id="requirement-text"
        aria-labelledby="requirement-text-heading"
        name="requirementText"
        value={requirementText}
        onChange={(event) => {
          if (canEditRequirements) setRequirementText(event.target.value);
        }}
        placeholder="用一段话描述你的系统：做什么、给谁用、有哪些角色和关键流程，越具体越能抽出准确的需求规则"
        disabled={!canEditRequirements}
        title={!canEditRequirements ? editBlockedReason : undefined}
        className={cn(
          "relative mt-3 w-full resize-y rounded-lg border border-input bg-background px-4 py-4 text-sm leading-relaxed text-foreground outline-none transition-colors placeholder:text-muted-foreground focus:border-primary/60 focus:ring-2 focus:ring-primary/15",
          !canEditRequirements &&
            "cursor-not-allowed bg-muted/40 text-muted-foreground",
          mode === "empty" ? "h-[clamp(360px,48vh,620px)] min-h-80" : "h-[240px]",
        )}
      />
      <div className="relative mt-6 flex flex-wrap items-center gap-2">
        <ModelPicker
          value={defaultModel}
          onValueChange={updateModel}
          disabled={!canRunGeneration}
        />
        {isRulesStale && (
          <Badge variant="warning" className="rounded-md px-1.5 py-0 text-[11px]">
            需求已修改
          </Badge>
        )}
        <Button
          type="button"
          variant="outline"
          size="sm"
          className="ml-auto h-10 rounded-full px-6"
          onClick={() => setRequirementText("")}
          disabled={!requirementText || generating || !canEditRequirements}
          title={!canEditRequirements ? editBlockedReason : undefined}
        >
          清空
        </Button>
        <button
          type="button"
          onClick={runGenerateRules}
          disabled={!requirementText.trim() || generating || !canRunGeneration}
          title={
            !canRunGeneration
              ? generationBlockedByPermissionReason
              : isRulesStale
                ? "更新需求规则"
                : "生成需求规则"
          }
          className="inline-flex h-10 items-center gap-2 rounded-full bg-primary px-6 text-sm font-medium text-primary-foreground shadow-sm transition-opacity hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-40"
        >
          {generating ? (
            <Loader2 className="size-4 animate-spin" />
          ) : (
            <ArrowUp className="size-4" />
          )}
          {isRulesStale ? "更新需求规则" : "开始分析提取"}
        </button>
      </div>
    </div>
  );

  const renderRequirementRules = () => (
    <section className="overflow-hidden rounded-xl border border-border bg-card shadow-sm">
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-border bg-muted/40 px-6 py-6">
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2">
            <ListChecks className="size-5 text-primary" />
            <h2 className="text-xl font-semibold tracking-normal text-foreground">
              需求规则
            </h2>
          </div>
          <Badge
            variant="secondary"
            className="rounded-full border-0 px-2.5 py-0.5 font-mono text-xs font-bold"
          >
            {rules.length}
          </Badge>
        </div>
        <div className="flex flex-wrap items-center gap-4">
          <div className="relative w-64">
            <Search className="absolute left-3 top-1/2 size-3.5 -translate-y-1/2 text-muted-foreground" />
            <Input
              value={query}
              onChange={(event) => setQuery(event.target.value)}
              placeholder="搜索规则..."
              className="h-9 rounded-lg bg-background pl-9 text-sm"
            />
          </div>
          <SelectControl
            value={ruleCategoryFilter}
            onValueChange={(value) =>
              setRuleCategoryFilter(
                value as RequirementRule["category"] | typeof ALL_RULE_CATEGORIES,
              )
            }
            className="h-9 w-36 rounded-lg bg-background text-sm"
            aria-label="需求类型筛选"
            options={[
              { value: ALL_RULE_CATEGORIES, label: "全部类型" },
              ...RULE_CATEGORY_ORDER.map((category) => ({
                value: category,
                label: category,
              })),
            ]}
          />
          <Button
            type="button"
            size="sm"
            variant="outline"
            className="h-9 rounded-lg bg-background px-4"
            onClick={() => setNewRuleDialogOpen(true)}
            disabled={generating || !canEditRequirements}
            title={!canEditRequirements ? editBlockedReason : undefined}
          >
            <Plus className="size-3.5" /> 新增需求项
          </Button>
        </div>
      </div>
      <div className="overflow-x-auto">
        <table className="w-full table-fixed border-collapse bg-card text-sm">
          <thead className="text-xs tracking-[0.02em] text-muted-foreground">
            <tr className="border-b border-border">
              <th className="w-[84px] px-6 py-4 text-left font-medium">编号</th>
              <th className="w-36 px-6 py-4 text-left font-medium">类型</th>
              <th className="w-52 px-4 py-4 text-left font-medium">状态</th>
              <th className="px-6 py-4 text-left font-medium">需求文本内容</th>
              <th className="w-28 px-6 py-4 text-right font-medium">操作</th>
            </tr>
          </thead>
          <tbody>
            {filteredRules.length === 0 ? (
              <tr
                data-testid="requirement-rule-row-slot"
                className={cn(RULE_ROW_CLASS, "border-b border-border")}
              >
                <td
                  colSpan={5}
                  className="px-6 py-3 text-center align-middle text-sm text-muted-foreground"
                >
                  没有匹配的规则。
                </td>
              </tr>
            ) : (
              pagedRules.map((rule) => {
              const requirement = requirementByRuleId.get(rule.id);
              const qualityIssues = requirement
                ? qualityIssuesByRequirementId.get(requirement.id) ?? []
                : [];
              const rowState = requirementRowState(requirement, qualityIssues);
              const candidate = requirementReviewCandidates[rule.id];
              const displayRowState = reviewCandidateStateLabel(candidate, rowState);
              const reviewDecisionLabel = reviewCandidateDecisionLabel(candidate);
              const hintCount = requirementHintCount(requirement) + qualityIssues.length;
              const hasHintDetails = Boolean(
                requirement && (hintCount > 0 || candidate),
              );
              const statusContent = displayRowState ? (
                <>
                  <Badge
                    variant="outline"
                    className={cn(
                      "max-w-[112px] rounded-md px-2 py-1 text-xs",
                      candidate?.status === "failed"
                        ? "border-destructive/40 bg-destructive/10 text-destructive"
                        : requirementStateTone(displayRowState),
                    )}
                  >
                    <span className="truncate">{displayRowState}</span>
                  </Badge>
                  {reviewDecisionLabel && (
                    <Badge variant="success" className="shrink-0 rounded-md px-1.5 py-0.5 text-[11px]">
                      {reviewDecisionLabel}
                    </Badge>
                  )}
                  {hintCount > 0 && (
                    <Badge variant="warning" className="shrink-0 rounded-md px-1.5 py-0.5 text-[11px]">
                      {hintCount}项
                    </Badge>
                  )}
                </>
              ) : null;
              return (
                <tr
                  key={rule.id}
                  id={`rule-${rule.id}`}
                  data-testid="requirement-rule-row-slot"
                  className={cn(
                    RULE_ROW_CLASS,
                    "border-b border-border transition-colors hover:bg-muted/30",
                  )}
                >
                    <td className="px-6 py-3 align-middle">
                      <span className="font-mono text-xs uppercase text-muted-foreground">
                        {rule.id}
                      </span>
                    </td>
                    <td className="px-6 py-3 align-middle">
                      <SelectControl
                        value={rule.category}
                        onValueChange={(value) =>
                          canEditRequirements
                            ? updateRequirementRule(rule.id, {
                                category: value as RequirementRule["category"],
                              })
                            : undefined
                        }
                        className="h-8 w-full rounded-md bg-background text-xs"
                        contentClassName="min-w-[8rem]"
                        aria-label={`需求类型 ${rule.id}`}
                        disabled={generating || !canEditRequirements}
                        options={RULE_CATEGORY_ORDER.map((category) => ({
                          value: category,
                          label: category,
                        }))}
                      />
                    </td>
                    <td className="px-4 py-3 align-middle">
                      {displayRowState && (
                        <div className="flex min-w-0 items-center gap-1.5 overflow-hidden whitespace-nowrap">
                          {hasHintDetails ? (
                            <button
                              type="button"
                              className="inline-flex min-w-0 items-center gap-1.5 overflow-hidden rounded-md text-left transition-colors hover:bg-warning/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-warning/40"
                              aria-label={`需求提示详情 ${rule.id}`}
                              onClick={() => setHintDetailRuleId(rule.id)}
                            >
                              {statusContent}
                            </button>
                          ) : (
                            statusContent
                          )}
                        </div>
                      )}
                    </td>
                    <td className="min-w-0 px-6 py-3 align-middle">
                      <input
                        type="text"
                        value={rule.text}
                        onChange={(event) =>
                          canEditRequirements
                            ? updateRequirementRule(rule.id, {
                                text: event.target.value,
                              })
                            : undefined
                        }
                        className="h-8 w-full min-w-0 truncate rounded-md border border-transparent bg-transparent px-0 text-sm text-foreground outline-none transition-colors hover:border-border hover:bg-background focus:border-primary/60 focus:bg-background focus:px-2 focus:ring-2 focus:ring-primary/15"
                        disabled={generating || !canEditRequirements}
                        title={!canEditRequirements ? editBlockedReason : rule.text}
                      />
                    </td>
                    <td className="px-6 py-3 text-right align-middle">
                      <Button
                        type="button"
                        size="sm"
                        variant="ghost"
                        className="h-8 px-2 text-muted-foreground hover:bg-destructive/10 hover:text-destructive"
                        onClick={() => deleteRequirementRule(rule.id)}
                        disabled={generating || !canEditRequirements}
                        title={!canEditRequirements ? editBlockedReason : undefined}
                        aria-label={`删除需求项 ${rule.id}`}
                      >
                        <Trash2 className="size-3.5" />
                      </Button>
                    </td>
                  </tr>
                );
              })
            )}
            {Array.from({
              length:
                filteredRules.length === 0
                  ? Math.max(0, rulePageSize - 1)
                  : emptyRuleSlots,
            }).map((_, index) => (
              <tr
                key={`empty-rule-slot:${safeRulePage}:${index}`}
                data-testid="requirement-rule-row-slot"
                aria-hidden="true"
                className={cn(RULE_ROW_CLASS, "border-b border-border")}
              >
                <td colSpan={5} className="px-6 py-3">
                  &nbsp;
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div
        data-testid="requirement-rule-pagination"
        className="sticky bottom-0 z-10 flex flex-wrap items-center justify-between gap-3 border-t border-border bg-muted/95 px-6 py-4 text-xs text-muted-foreground shadow-lg backdrop-blur"
      >
        <div className="flex flex-wrap items-center gap-3">
          <span>
            {firstRuleIndex}-{lastRuleIndex} / {filteredRules.length}
          </span>
          <SelectControl
            value={String(rulePageSize)}
            onValueChange={(value) => {
              setRulePageSize(Number(value));
              setCurrentRulePage(1);
            }}
            className="h-8 w-28 rounded-md bg-background text-xs"
            contentClassName="min-w-[7rem]"
            aria-label="每页需求规则数量"
            options={RULE_PAGE_SIZE_OPTIONS.map((pageSize) => ({
              value: String(pageSize),
              label: `每页 ${pageSize} 条`,
            }))}
          />
        </div>
        <div className="flex items-center gap-1.5">
          <button
            type="button"
            aria-label="上一页"
            onClick={() => setCurrentRulePage((page) => Math.max(1, page - 1))}
            disabled={safeRulePage === 1}
            className="inline-flex size-8 items-center justify-center rounded-md border border-border bg-background text-foreground transition-colors hover:bg-accent hover:text-accent-foreground disabled:cursor-not-allowed disabled:opacity-40"
          >
            <ChevronLeft className="size-4" />
          </button>
          {Array.from({ length: totalRulePages }, (_, index) => index + 1).map(
            (page) => (
              <button
                type="button"
                key={page}
                onClick={() => setCurrentRulePage(page)}
                className={cn(
                  "inline-flex size-8 items-center justify-center rounded-md border text-xs font-medium transition-colors",
                  page === safeRulePage
                    ? "border-primary bg-primary text-primary-foreground"
                    : "border-border bg-background text-foreground hover:bg-accent hover:text-accent-foreground",
                )}
              >
                {page}
              </button>
            ),
          )}
          <button
            type="button"
            aria-label="下一页"
            onClick={() =>
              setCurrentRulePage((page) => Math.min(totalRulePages, page + 1))
            }
            disabled={safeRulePage === totalRulePages}
            className="inline-flex size-8 items-center justify-center rounded-md border border-border bg-background text-foreground transition-colors hover:bg-accent hover:text-accent-foreground disabled:cursor-not-allowed disabled:opacity-40"
          >
            <ChevronRight className="size-4" />
          </button>
        </div>
      </div>
    </section>
  );

  const renderAssistantPanel = () => (
    <aside className="flex min-h-0 flex-col overflow-hidden rounded-xl border border-border bg-card shadow-sm">
      <div className="flex items-center gap-2 border-b border-border bg-muted/40 px-4 py-3">
        <Bot className="size-4 text-primary" />
        <h2 className="text-sm font-semibold text-foreground">AI 需求助手</h2>
      </div>
      <div className="flex min-h-0 flex-1 flex-col gap-3 overflow-auto p-3">
        <div className="rounded-bl-lg rounded-br-lg rounded-tr-lg bg-muted px-3 py-2 text-xs leading-5 text-foreground">
          你好！我是您的需求分析助手。我可以帮助您细化功能点、完善业务规则或根据您的想法提供专业建议。请问有什么可以帮您的？
        </div>
        <MobileRail className="md:grid-cols-1">
            {REQUIREMENT_TEMPLATE_CARDS.map(
              ({ title, english, description, templateText, Icon }) => (
                <MobileRailCard key={title} className="min-w-[172px]">
                  <button
                    type="button"
                    onClick={() => setRequirementText(templateText)}
                    disabled={!canEditRequirements}
                    title={!canEditRequirements ? editBlockedReason : undefined}
                    className={cn(
                      "group flex h-full min-h-[118px] w-full flex-col rounded-lg border border-border bg-background p-2 text-left shadow-sm transition-all duration-200 hover:border-primary/40 hover:bg-accent/40 hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring md:min-h-0",
                      mobileTouchTargetClass,
                    )}
                  >
                    <span className="flex items-center gap-2">
                      <span className="inline-flex size-8 shrink-0 items-center justify-center rounded-md bg-primary/10 text-primary transition-colors group-hover:bg-primary/15">
                        <Icon className="size-3.5" />
                      </span>
                      <span className="min-w-0 flex-1">
                        <span className="block truncate text-xs font-semibold text-foreground">
                          {title}
                        </span>
                        <span className="block truncate font-mono text-[9px] text-muted-foreground">
                          {english}
                        </span>
                      </span>
                    </span>
                    <span className="mt-2 line-clamp-2 text-[11px] leading-4 text-muted-foreground">
                          {description}
                    </span>
                    <span className="mt-auto inline-flex items-center gap-1 pt-2 text-[11px] font-medium text-primary">
                      <CircleCheck className="size-3" />
                      应用模板
                    </span>
                  </button>
                </MobileRailCard>
              ),
            )}
        </MobileRail>
      </div>
      <div className="border-t border-border p-3">
        <div className="relative">
          <Input
            value=""
            readOnly
            disabled
            placeholder="输入消息..."
            className="h-9 rounded-full bg-muted pr-9 text-xs"
            aria-label="AI 需求助手输入消息"
          />
          <button
            type="button"
            disabled
            className="absolute right-1.5 top-1/2 inline-flex size-6 -translate-y-1/2 items-center justify-center rounded-full text-primary opacity-70"
            aria-label="发送消息"
          >
            <SendHorizontal className="size-3.5" />
          </button>
        </div>
      </div>
    </aside>
  );

  const pendingReviewCandidate =
    visibleHintDetail?.candidate?.status === "pending"
      ? visibleHintDetail.candidate
      : null;
  const failedReviewCandidate =
    visibleHintDetail?.candidate?.status === "failed"
      ? visibleHintDetail.candidate
      : null;
  const hasConfirmableQualityHint =
    Boolean(visibleHintDetail) &&
    !pendingReviewCandidate &&
    !failedReviewCandidate &&
    (visibleHintDetail?.rowState === "有待确认提示" ||
      visibleHintDetail?.requirement.status !== "accepted" ||
      (visibleHintDetail?.qualityIssues.length ?? 0) > 0);

  return (
    <div className="flex h-full min-h-0 flex-col overflow-auto bg-background">
      {showStaleBanner && isRulesStale && (
        <div className="flex items-center gap-2 border-b border-warning/40 bg-warning/10 px-3 py-2 text-sm">
          <AlertTriangle className="size-4 text-warning" />
          <span>需求文本已修改，下方规则基于旧文本，可能已过时。</span>
          <Button
            size="sm"
            variant="outline"
            className="ml-auto h-7"
            onClick={runGenerateRules}
            disabled={generating || !canRunGeneration}
            title={!canRunGeneration ? generationBlockedByPermissionReason : undefined}
          >
            <RefreshCw className="size-3.5" /> 重新生成规则
          </Button>
        </div>
      )}

      {showStaleBanner && staleDiagrams.length > 0 && (
        <div className="flex items-center gap-2 border-b border-warning/40 bg-warning/10 px-3 py-2 text-sm">
          <AlertTriangle className="size-4 text-warning" />
          <span>
            {staleDiagrams.length} 个模型基于旧规则：
            {staleDiagrams.map((diagram) => DIAGRAM_META[diagram].label).join("、")}
          </span>
          <Button
            size="sm"
            variant="outline"
            className="ml-auto h-7"
            onClick={() => runGenerateDiagrams(staleDiagrams)}
            disabled={
              generating ||
              Boolean(requirementReviewBlockedReason) ||
              !canRunGeneration
            }
            title={
              !canRunGeneration
                ? generationBlockedByPermissionReason
                : generationBlockedTitle
            }
          >
            <RefreshCw className="size-3.5" /> 仅更新过时模型
          </Button>
        </div>
      )}

      <div className="w-full py-4 lg:py-5">
        <div className="mx-auto flex w-[calc(100%-1.5rem)] max-w-none flex-col gap-5 sm:w-[calc(100%-2rem)] lg:w-[calc(100%-3rem)]">
          <header className="flex flex-col gap-1.5">
            <h1 className="text-2xl font-semibold tracking-normal text-foreground lg:text-3xl">
              需求分析提取
            </h1>
            <p className="max-w-3xl text-sm leading-6 text-muted-foreground">
              输入您的项目需求描述，系统将帮助您提取关键用例、参与者并生成初始的系统模型。
            </p>
            {!canEditRequirements && (
              <div className="mt-2 inline-flex max-w-3xl items-center gap-2 rounded-lg border border-warning/30 bg-warning/10 px-3 py-2 text-xs text-warning">
                <AlertTriangle className="size-3.5" />
                {editBlockedReason}
              </div>
            )}
            {billingGenerationBlock && (
              <div className="mt-2 flex max-w-4xl flex-wrap items-center gap-3 rounded-lg border border-warning/30 bg-warning/10 px-3 py-2 text-sm text-foreground">
                <AlertTriangle className="size-4 text-warning" />
                <div className="min-w-0 flex-1">
                  <div className="font-medium">{billingGenerationBlock.message}</div>
                  <div className="text-xs text-muted-foreground">
                    可用次数 {billingGenerationBlock.billingSummary.creditBalance}，
                    {billingGenerationBlock.billingSummary.activePass
                      ? `通行卡今日 ${billingGenerationBlock.billingSummary.passDailyUsage.usedToday}/${billingGenerationBlock.billingSummary.passDailyUsage.limit}`
                      : "当前没有有效通行卡"}
                  </div>
                </div>
                <Button asChild size="sm" className="h-8">
                  <a href="/pricing">购买权益</a>
                </Button>
                <Button asChild size="sm" variant="outline" className="h-8 bg-card">
                  <a href="/account/billing">账单</a>
                </Button>
                <Button
                  type="button"
                  size="icon"
                  variant="ghost"
                  className="size-8"
                  aria-label="关闭权益提示"
                  onClick={clearBillingGenerationBlock}
                >
                  <X className="size-4" />
                </Button>
              </div>
            )}
          </header>
          <div className="grid grid-cols-1 gap-4 xl:grid-cols-[minmax(0,1fr)_minmax(220px,260px)]">
            <div className="grid min-w-0 gap-4">
              {renderRequirementInput(hasGeneratedRules ? "generated" : "empty")}
              {hasGeneratedRules && renderRequirementRules()}
            </div>
            {renderAssistantPanel()}
          </div>

          <section className="flex flex-col gap-4">
            <div className="flex flex-wrap items-center justify-between gap-4">
              <div className="flex items-center gap-2">
                <Network className="size-5 text-primary" />
                <h2 className="text-xl font-semibold tracking-normal text-foreground">
                  目标模型
                </h2>
              </div>
              <Badge
                variant="secondary"
                className="rounded-md border-0 px-3 py-1 font-mono text-xs"
              >
                {selectedDiagrams.length}/{DIAGRAM_ORDER.length}
              </Badge>
              <div className="ml-auto flex items-center gap-2">
                {requirementModelRepairRecords.length > 0 && (
                  <Button
                    type="button"
                    size="sm"
                    variant="outline"
                    className="h-9 rounded-lg bg-card"
                    aria-label={`查看需求模型追踪证明，共 ${requirementModelRepairRecords.length} 项`}
                    onClick={() => setTraceabilityDialogOpen(true)}
                  >
                    <Eye className="size-3.5" />
                    追踪证明
                    <span className="rounded border border-border bg-muted px-1.5 py-0.5 font-mono text-[10px]">
                      {requirementModelRepairRecords.length}项
                    </span>
                  </Button>
                )}
                <ModelPicker
                  value={defaultModel}
                  onValueChange={updateModel}
                  align="end"
                  triggerClassName="bg-card"
                  disabled={!canRunGeneration}
                />
                <button
                  type="button"
                  onClick={() => runGenerateDiagrams()}
                  disabled={
                    selectedDiagrams.length === 0 ||
                    generating ||
                    Boolean(requirementReviewBlockedReason) ||
                    Boolean(selectedTargetBlockReason) ||
                    !canRunGeneration
                  }
                  title={
                    !canRunGeneration
                      ? generationBlockedByPermissionReason
                      : selectedTargetBlockReason ?? generationBlockedTitle
                  }
                  className="inline-flex h-9 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-medium text-primary-foreground shadow-sm transition-opacity hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-40"
                >
                  {generating ? (
                    <Loader2 className="size-4 animate-spin" />
                  ) : (
                    <Wand2 className="size-4" />
                  )}
                  {generateDiagramsButtonLabel}
                </button>
              </div>
            </div>
            {requirementReviewBlockedReason && (
              <div className="flex items-center gap-1.5 rounded-lg border border-warning/30 bg-warning/10 px-3 py-2 text-xs text-warning">
                <AlertTriangle className="size-3.5" />
                {requirementReviewBlockedReason}
              </div>
            )}

            <MobileCompactGrid className="grid-cols-1 md:grid-cols-2 2xl:grid-cols-3">
              {DIAGRAM_ORDER.map((diagram) => {
                const meta = DIAGRAM_META[diagram];
                const checked = selectedDiagrams.includes(diagram);
                const linkedRules = rules.filter((rule) =>
                  rule.relatedDiagrams.includes(diagram),
                );
                const isAnalysisDiagram = diagram === "analysis";
                const canGenerateSelectedUseCase =
                  selectedDiagrams.includes("usecase") &&
                  (rules.length > 0 || hasRequirementSourceText);
                const hasUseCaseSourceForAnalysis =
                  generatedDiagrams.includes("usecase") ||
                  canGenerateSelectedUseCase;
                const blockReason = getRequirementTargetBlockReason(diagram);
                const canSelectDiagram = canEditRequirements && !blockReason;
                const autoFillLabels = [
                  !isAnalysisDiagram &&
                  rules.length === 0 &&
                  hasRequirementSourceText
                    ? "需求规则"
                    : null,
                  !isAnalysisDiagram && rules.length > 0 && linkedRules.length === 0
                    ? "规则映射"
                    : null,
                  isAnalysisDiagram && !hasUseCaseSourceForAnalysis
                    ? DIAGRAM_META.usecase.label
                    : null,
                ].filter((label): label is string => Boolean(label));
                const pendingAutoReviews =
                  pendingAutoReviewsForRequirementDiagram(
                    autoGeneratedUpstreamReviews,
                    diagram,
                  );
                const hasPendingAutoReview = pendingAutoReviews.length > 0;
                const sourceCount = isAnalysisDiagram
                  ? Number(hasUseCaseSourceForAnalysis)
                  : linkedRules.length;
                const DiagramIcon = REQUIREMENT_DIAGRAM_ICON[diagram];
                return (
                  <ModelBentoCard
                    key={diagram}
                    label={meta.label}
                    english={meta.english}
                    description={meta.description}
                    icon={DiagramIcon}
                    selected={checked}
                    disabled={!canSelectDiagram}
                    countLabel={sourceCount}
                    pendingReview={hasPendingAutoReview}
                    title={
                      !canEditRequirements ? editBlockedReason : undefined
                    }
                    ariaLabel={`${checked ? "取消选择" : "选择"}${meta.label}`}
                    checkboxLabel={meta.label}
                    onSelectedChange={(value) => toggleDiagram(diagram, value)}
                    status={
                      <div className="space-y-1.5">
                        {hasPendingAutoReview && (
                          <div className="rounded-md border border-warning/30 bg-warning/10 p-2 text-warning">
                            <div className="flex items-start gap-1.5">
                              <AlertTriangle className="mt-0.5 size-3.5 shrink-0" />
                              <span>
                                自动补齐待确认：
                                {pendingAutoReviews
                                  .map((review) => review.label)
                                  .join("、")}
                              </span>
                            </div>
                            <div className="mt-2 flex flex-wrap gap-2">
                              <Button
                                type="button"
                                size="sm"
                                variant="outline"
                                className="h-7 rounded-md px-2 text-[11px]"
                                aria-label={`采纳${meta.label}自动补齐`}
                                onClick={(event) =>
                                  decideAutoReviews(
                                    event,
                                    pendingAutoReviews,
                                    "accepted",
                                  )
                                }
                              >
                                采纳补齐
                              </Button>
                              <Button
                                type="button"
                                size="sm"
                                variant="ghost"
                                className="h-7 rounded-md px-2 text-[11px]"
                                aria-label={`忽略${meta.label}自动补齐`}
                                onClick={(event) =>
                                  decideAutoReviews(
                                    event,
                                    pendingAutoReviews,
                                    "dismissed",
                                  )
                                }
                              >
                                忽略提示
                              </Button>
                            </div>
                          </div>
                        )}
                        {!canSelectDiagram && (
                          <div className="flex items-center gap-1.5 text-destructive">
                            <AlertTriangle className="size-3.5 shrink-0" />
                            <span>
                              {blockReason ??
                                (isAnalysisDiagram
                                  ? "需先选择或生成用例模型"
                                  : "缺少对应需求规则")}
                            </span>
                          </div>
                        )}
                        {autoFillLabels.length > 0 && !blockReason && (
                          <div className="flex items-center gap-1.5 text-warning">
                            <AlertTriangle className="size-3.5 shrink-0" />
                            <span>将自动补齐：{autoFillLabels.join("、")}</span>
                          </div>
                        )}
                        {isAnalysisDiagram &&
                          canSelectDiagram &&
                          linkedRules.length === 0 && (
                            <div className="text-muted-foreground">
                              基于用例模型事件流生成，不要求需求规则直接映射。
                            </div>
                          )}
                        {canSelectDiagram &&
                          autoFillLabels.length === 0 &&
                          !(
                            isAnalysisDiagram && linkedRules.length === 0
                          ) && (
                            <div className="text-muted-foreground">
                              已关联来源：{sourceCount}
                            </div>
                          )}
                      </div>
                    }
                    details={
                      linkedRules.length > 0 ? (
                        <div className="hidden flex-wrap gap-1.5 sm:flex">
                          {linkedRules.map((rule) => (
                            <button
                              type="button"
                              key={rule.id}
                              title={rule.text}
                              onClick={(event) => {
                                event.stopPropagation();
                                const element = document.getElementById(
                                  `rule-${rule.id}`,
                                );
                                if (element) {
                                  element.scrollIntoView({
                                    behavior: "smooth",
                                    block: "center",
                                  });
                                  element.classList.add("ring-2", "ring-primary/40");
                                  setTimeout(() => {
                                    element.classList.remove(
                                      "ring-2",
                                      "ring-primary/40",
                                    );
                                  }, 1200);
                                }
                              }}
                              onKeyDown={(event) => event.stopPropagation()}
                              className="rounded border border-border bg-secondary px-2 py-0.5 font-mono text-[10px] uppercase text-muted-foreground transition-colors hover:border-primary/40 hover:bg-accent hover:text-accent-foreground"
                            >
                              {rule.id}
                            </button>
                          ))}
                        </div>
                      ) : null
                    }
                  />
                );
              })}
            </MobileCompactGrid>
            <p className="pb-4 text-center text-xs text-muted-foreground">
              勾选不会立即生效；点击「生成模型」后左侧菜单才会更新。之后生成需求模型、设计模型、代码原型和说明书时，都会优先使用这里选择的需求项。
            </p>
          </section>
        </div>
      </div>

      <Dialog
        open={Boolean(hintDetail)}
        onOpenChange={(open) => {
          if (!open) setHintDetailRuleId(null);
        }}
      >
        <DialogContent className="sm:max-w-2xl">
          <DialogHeader>
            <DialogTitle>
              {pendingReviewCandidate ? "需求规则修复确认" : "需求质量提示"}
            </DialogTitle>
            <DialogDescription>
              {pendingReviewCandidate
                ? "对比修复前后的结构化需求，采纳或拒绝后都会标记为已确认。"
                : "查看当前需求的待确认原因；可确认当前提示，或生成修复结果后再采纳/拒绝。"}
            </DialogDescription>
          </DialogHeader>
          {visibleHintDetail && (
            <div className="max-h-[60vh] overflow-auto pr-1">
              <div className="rounded-lg border border-border bg-muted/30 p-3 text-sm">
                <div className="flex flex-wrap items-center gap-2">
                  <span className="font-mono text-xs uppercase text-muted-foreground">
                    {visibleHintDetail.rule.id}
                  </span>
                  <Badge
                    variant="outline"
                    className={cn(
                      "rounded-md px-2 py-1 text-xs",
                      requirementStateTone(visibleHintDetail.rowState),
                    )}
                  >
                    {visibleHintDetail.rowState}
                  </Badge>
                  <span className="text-xs text-muted-foreground">
                    {visibleHintDetail.requirement.id}
                  </span>
                </div>
                <div className="mt-2 text-foreground">
                  {visibleHintDetail.rule.text}
                </div>
              </div>

              {visibleHintDetail.candidate && (
                <div className="mt-4">
                  <h3 className="text-sm font-semibold text-foreground">
                    修复前后对比
                  </h3>
                  {visibleHintDetail.candidate.status === "failed" ? (
                    <div className="mt-2 rounded-lg border border-destructive/30 bg-destructive/10 px-3 py-2 text-xs leading-5 text-destructive">
                      {visibleHintDetail.candidate.errorMessage ??
                        "当前规则修复失败，请重新修复。"}
                    </div>
                  ) : (
                    <div className="mt-2 overflow-hidden rounded-lg border border-border">
                      <div className="grid grid-cols-[120px_1fr_1fr] border-b border-border bg-muted/40 text-xs font-medium text-muted-foreground">
                        <div className="px-3 py-2">字段</div>
                        <div className="px-3 py-2">修复前</div>
                        <div className="px-3 py-2">修复后</div>
                      </div>
                      {REVIEWABLE_REQUIREMENT_FIELDS.map((field) => {
                        const beforeValue = requirementFieldValue(
                          visibleHintDetail.candidate.beforeRequirement,
                          field,
                        );
                        const afterRequirement =
                          visibleHintDetail.candidate.afterRequirement ??
                          visibleHintDetail.candidate.beforeRequirement;
                        const afterValue = requirementFieldValue(afterRequirement, field);
                        const changed = beforeValue !== afterValue;
                        return (
                          <div
                            key={field}
                            className="grid grid-cols-[120px_1fr_1fr] border-b border-border last:border-b-0 text-xs leading-5"
                          >
                            <div className="px-3 py-2 font-medium text-foreground">
                              {REQUIREMENT_FIELD_LABELS[field]}
                            </div>
                            <div className="px-3 py-2 text-muted-foreground">
                              {beforeValue || "暂无字段值"}
                            </div>
                            <div
                              className={cn(
                                "px-3 py-2 text-foreground",
                                changed && "bg-success/10 text-success",
                              )}
                            >
                              {afterValue || "暂无字段值"}
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  )}
                  {visibleHintDetail.candidate.repairRationale && (
                    <div className="mt-2 rounded-lg border border-border bg-muted/30 px-3 py-2 text-xs leading-5 text-muted-foreground">
                      {visibleHintDetail.candidate.repairRationale}
                    </div>
                  )}
                  {visibleHintDetail.candidate.blockingReasons.length > 0 && (
                    <div className="mt-2 grid gap-1">
                      {visibleHintDetail.candidate.blockingReasons.map((reason) => (
                        <div
                          key={reason}
                          className="rounded-lg border border-warning/30 bg-warning/10 px-3 py-2 text-xs leading-5 text-warning"
                        >
                          {reason}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}

              <div className="mt-4">
                <h3 className="text-sm font-semibold text-foreground">
                  字段来源与待确认项
                </h3>
                <div className="mt-2 grid gap-2">
                  {visibleHintDetail.fieldEntries.length > 0 ? (
                    visibleHintDetail.fieldEntries.map(([field, provenance]) => (
                      <div
                        key={field}
                        className="rounded-lg border border-border bg-card px-3 py-2 text-xs leading-5"
                      >
                        <div className="flex flex-wrap items-center gap-2">
                          <span className="font-medium text-foreground">
                            {REQUIREMENT_FIELD_LABELS[field]}
                          </span>
                          <Badge
                            variant="outline"
                            className="rounded-md px-1.5 py-0 text-[10px]"
                          >
                            {requirementSourceLabel(provenance.source)}
                          </Badge>
                          <span className="text-muted-foreground">
                            {requirementFieldStatusLabel(provenance.status)}
                          </span>
                        </div>
                        <div className="mt-1 text-foreground">
                          {requirementFieldValue(visibleHintDetail.requirement, field) ||
                            "暂无字段值"}
                        </div>
                        {provenance.rationale && (
                          <div className="mt-1 text-muted-foreground">
                            {provenance.rationale}
                          </div>
                        )}
                      </div>
                    ))
                  ) : (
                    <div className="rounded-lg border border-border bg-muted/30 px-3 py-2 text-xs text-muted-foreground">
                      暂无字段来源提示。
                    </div>
                  )}
                </div>
              </div>

              <div className="mt-4">
                <h3 className="text-sm font-semibold text-foreground">质量提示</h3>
                <div className="mt-2 grid gap-2">
                  {visibleHintDetail.qualityIssues.length > 0 ? (
                    visibleHintDetail.qualityIssues.map((issue) => (
                      <div
                        key={issue.id}
                        className="rounded-lg border border-warning/30 bg-warning/10 px-3 py-2 text-xs leading-5 text-warning"
                      >
                        {issue.message}
                      </div>
                    ))
                  ) : (
                    <div className="rounded-lg border border-border bg-muted/30 px-3 py-2 text-xs text-muted-foreground">
                      暂无额外质量提示。
                    </div>
                  )}
                </div>
              </div>
          </div>
          )}
          <DialogFooter>
            {visibleHintDetail && failedReviewCandidate ? (
              <Button
                type="button"
                variant="outline"
                onClick={() => void repairRequirementRule(visibleHintDetail.rule.id)}
                disabled={generating}
              >
                重新修复
              </Button>
            ) : null}
            {visibleHintDetail && !visibleHintDetail.candidate ? (
              <Button
                type="button"
                variant="outline"
                onClick={() => void repairRequirementRule(visibleHintDetail.rule.id)}
                disabled={generating}
              >
                智能修复
              </Button>
            ) : null}
            {visibleHintDetail && hasConfirmableQualityHint ? (
              <Button
                type="button"
                onClick={() =>
                  void confirmRequirementQualityHint(
                    visibleHintDetail.rule.id,
                  ).then(() => setHintDetailRuleId(null))
                }
                disabled={generating}
              >
                确认提示
              </Button>
            ) : null}
            {pendingReviewCandidate ? (
              <>
                <Button
                  type="button"
                  variant="outline"
                  onClick={() =>
                    void decideRequirementReviewCandidate(
                      visibleHintDetail.rule.id,
                      "rejected",
                    ).then(() => setHintDetailRuleId(null))
                  }
                  disabled={generating}
                >
                  拒绝
                </Button>
                <Button
                  type="button"
                  onClick={() =>
                    void decideRequirementReviewCandidate(
                      visibleHintDetail.rule.id,
                      "accepted",
                    ).then(() => setHintDetailRuleId(null))
                  }
                  disabled={generating}
                >
                  采纳
                </Button>
              </>
            ) : (
              <Button type="button" onClick={() => setHintDetailRuleId(null)}>
                关闭
              </Button>
            )}
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={traceabilityDialogOpen} onOpenChange={setTraceabilityDialogOpen}>
        <DialogContent className="sm:max-w-2xl">
          <DialogHeader>
            <DialogTitle>需求模型追踪证明</DialogTitle>
            <DialogDescription>
              查看需求规则到需求模型元素的覆盖解释；这些内容用于审计和排查，不影响当前页面编辑。
            </DialogDescription>
          </DialogHeader>
          <div className="max-h-[60vh] overflow-auto pr-1">
            <div className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-border bg-muted/30 p-3">
              <div>
                <div className="text-sm font-medium text-foreground">
                  覆盖证明
                </div>
                <div className="mt-1 text-xs text-muted-foreground">
                  共 {requirementModelRepairRecords.length} 项
                </div>
              </div>
              <Badge
                variant="outline"
                className="border-success/35 bg-success/10 text-success"
              >
                证明已补齐
              </Badge>
            </div>
            <div className="mt-3 grid gap-2">
              {requirementModelRepairRecords.map((record) => (
                <div
                  key={record.id}
                  className="rounded-lg border border-border bg-muted/30 px-3 py-2 text-xs leading-5"
                >
                  <div className="text-muted-foreground">
                    问题原因：{stageRepairCopy(record.reason)}
                  </div>
                  <div className="mt-1 text-foreground">
                    补齐方式：{stageRepairCopy(record.repair)}
                  </div>
                  <div className="mt-1 font-medium text-success">
                    证明状态：{record.status}
                  </div>
                  <Button
                    type="button"
                    size="sm"
                    variant="outline"
                    className="mt-2 h-8"
                    onClick={() =>
                      setModelRepairResult({ targetLabel: record.targetLabel })
                    }
                  >
                    重新补齐证明
                  </Button>
                </div>
              ))}
            </div>
          </div>
          <DialogFooter>
            <Button type="button" onClick={() => setTraceabilityDialogOpen(false)}>
              关闭
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog
        open={Boolean(modelRepairResult)}
        onOpenChange={(open) => {
          if (!open) setModelRepairResult(null);
        }}
      >
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>单项证明补齐完成</DialogTitle>
            <DialogDescription>
              已只重新检查当前需求模型覆盖证明，没有重新生成全部需求模型。
            </DialogDescription>
          </DialogHeader>
          <div className="grid gap-2 rounded-md border border-border bg-muted/40 p-3 text-sm">
            <div>
              <span className="font-medium">阶段：</span>需求模型
            </div>
            <div>
              <span className="font-medium">对象：</span>
              {modelRepairResult?.targetLabel}
            </div>
          </div>
          <DialogFooter>
            <Button type="button" onClick={() => setModelRepairResult(null)}>
              我知道了
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog
        open={newRuleDialogOpen}
        onOpenChange={(open) => {
          setNewRuleDialogOpen(open);
          if (!open) resetNewRuleForm();
        }}
      >
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle>新增需求项</DialogTitle>
            <DialogDescription>
              新增时选择类型和对应模型；创建后列表中只允许修改文本内容。
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4">
            <label className="grid gap-1.5 text-sm">
              <span className="font-medium">需求类型</span>
              <SelectControl
                value={newRuleCategory}
                onValueChange={(value) => {
                  setNewRuleCategory(value as RequirementRule["category"]);
                  setNewRuleError(null);
                }}
                className="h-9"
                disabled={generating || !canEditRequirements}
                options={RULE_CATEGORY_ORDER.map((category) => ({
                  value: category,
                  label: category,
                }))}
              />
            </label>

            <div className="grid gap-2 text-sm">
              <span className="font-medium">对应模型</span>
              <div className="grid grid-cols-2 gap-2">
                {DIAGRAM_ORDER.map((diagram) => (
                  <label
                    key={`new-rule:${diagram}`}
                    className="inline-flex cursor-pointer items-center gap-2 rounded-md border border-border bg-background px-2 py-1.5 text-xs text-muted-foreground"
                  >
                    <Checkbox
                      checked={newRuleDiagrams.includes(diagram)}
                      onCheckedChange={(value) => {
                        toggleNewRuleDiagram(diagram, Boolean(value));
                        setNewRuleError(null);
                      }}
                      disabled={generating || !canEditRequirements}
                    />
                    {DIAGRAM_META[diagram].label}
                  </label>
                ))}
              </div>
            </div>

            <label className="grid gap-1.5 text-sm">
              <span className="font-medium">需求文本</span>
              <textarea
                value={newRuleText}
                onChange={(event) => {
                  setNewRuleText(event.target.value);
                  setNewRuleError(null);
                }}
                placeholder="填写这条需求项的具体内容"
                className="min-h-24 w-full resize-y rounded-md border border-input bg-background px-3 py-2 text-sm leading-relaxed outline-none focus:ring-2 focus:ring-ring"
                disabled={generating || !canEditRequirements}
              />
            </label>

            {newRuleError && (
              <div className="rounded-md border border-destructive/30 bg-destructive/5 px-3 py-2 text-xs text-destructive">
                {newRuleError}
              </div>
            )}
          </div>

          <DialogFooter className="gap-2 sm:gap-2">
            <Button
              type="button"
              variant="outline"
              onClick={() => setNewRuleDialogOpen(false)}
            >
              取消
            </Button>
            <Button
              type="button"
              onClick={submitNewRule}
              disabled={generating || !newRuleCanSubmit || !canEditRequirements}
            >
              创建需求项
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

    </div>
  );
}
