// Renders the requirement authoring page and coordinates rule editing, quality checks, and generation actions.
import { type MouseEvent, useEffect, useMemo, useRef, useState } from "react";
import {
  Wand2,
  Loader2,
  AlertTriangle,
  RefreshCw,
  ArrowUp,
  FileText,
  Network,
  Box,
  Server,
  GitBranch,
  Activity,
  Eye,
  X,
} from "lucide-react";
import { Button } from "../../../shared/ui/button";
import { Badge } from "../../../shared/ui/badge";
import { cn } from "../../../shared/ui/utils";
import type {
  AtomicRequirement,
  AtomicRequirementField,
  RequirementQualityIssue,
} from "@uml-platform/contracts";
import {
  DIAGRAM_META,
  DIAGRAM_ORDER,
  type DiagramType,
} from "../../../entities/diagram/model";
import {
  type RequirementRule,
} from "../../../entities/requirement-rule/model";
import { useWorkspaceSession } from "../../workspace-session/state";
import {
  buildRequirementModelRepairRecords,
  requirementDiagramsButtonLabel,
  requirementTargetBlockReason,
  requirementTargetCardState,
} from "../lib/requirement-target-view-model";
import {
  requirementRowState,
  type AutoGeneratedUpstreamReview,
} from "../lib/requirement-review-view-model";
import { ModelPicker } from "../../../shared/ui/model-picker";
import {
  loadUserSettings,
  patchUserSettings,
  USER_SETTINGS_CHANGED_EVENT,
} from "../../../shared/lib/user-settings";
import { ScaledToolbar } from "../../../shared/ui/scale-to-fit";
import {
  MobileCompactGrid,
} from "../../workspace-shell/components/mobile-density";
import { ModelBentoCard } from "../../workspace-shell/components/model-bento-card";
import {
  ALL_RULE_CATEGORIES,
  REQUIREMENT_RULES_PER_PAGE,
  RequirementRulesTable,
  type RequirementRuleCategoryFilter,
} from "./requirement-rules-table";
import {
  RequirementReviewDialog,
  type RequirementHintDetail,
} from "./requirement-review-dialog";
import {
  RequirementTraceabilityDialogs,
  type RequirementModelRepairResult,
} from "./requirement-traceability-dialogs";
import { NewRequirementRuleDialog } from "./new-requirement-rule-dialog";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "../../../shared/ui/dialog";

const DEFAULT_NEW_RULE_DIAGRAMS: DiagramType[] = ["function", "usecase", "activity"];
const REQUIREMENT_DIAGRAM_ICON = {
  function: FileText,
  usecase: Network,
  activity: Activity,
  class: Box,
  deployment: Server,
  prototype: Eye,
  analysis: GitBranch,
} satisfies Record<DiagramType, typeof Network>;

export function TextRequirementView() {
  const {
    requirementText,
    setRequirementText,
    rules,
    createRequirementRule,
    updateRequirementRule,
    deleteRequirementRule,
    selectedDiagrams,
    setSelectedDiagrams,
    generating,
    generateRules,
    generateDiagrams,
    isRulesStale,
    staleDiagrams,
    generatedDiagrams,
    requirementModelTraceability,
    autoGeneratedUpstreamReviews,
    decideAutoGeneratedUpstreamReview,
    requirementBaseline,
    requirementReviewCandidates,
    requirementReviewBlockedReason,
    repairRequirementRule,
    decideRequirementReviewCandidate,
    confirmRequirementQualityHint,
    canUpdateWorkspace,
    canStartRuns,
    workspacePermissionReason,
    billingGenerationBlock,
    clearBillingGenerationBlock,
  } = useWorkspaceSession();
  const [query, setQuery] = useState("");
  const [defaultModel, setDefaultModel] = useState(
    () => loadUserSettings().defaultModel,
  );
  const [showStaleBanner, setShowStaleBanner] = useState(
    () => loadUserSettings().showStaleBanner,
  );
  const [newRuleDialogOpen, setNewRuleDialogOpen] = useState(false);
  const [newRuleCategory, setNewRuleCategory] =
    useState<RequirementRule["category"]>("功能需求");
  const [newRuleDiagrams, setNewRuleDiagrams] = useState<DiagramType[]>(
    DEFAULT_NEW_RULE_DIAGRAMS,
  );
  const [newRuleText, setNewRuleText] = useState("");
  const [newRuleError, setNewRuleError] = useState<string | null>(null);
  const [modelRepairResult, setModelRepairResult] =
    useState<RequirementModelRepairResult | null>(null);
  const [hintDetailRuleId, setHintDetailRuleId] = useState<string | null>(null);
  const [traceabilityDialogOpen, setTraceabilityDialogOpen] = useState(false);
  const [ruleReplacementDialogOpen, setRuleReplacementDialogOpen] =
    useState(false);
  const [currentRulePage, setCurrentRulePage] = useState(1);
  const [rulePageSize, setRulePageSize] = useState(REQUIREMENT_RULES_PER_PAGE);
  const [ruleCategoryFilter, setRuleCategoryFilter] =
    useState<RequirementRuleCategoryFilter>(ALL_RULE_CATEGORIES);

  useEffect(() => {
    const syncSettings = () => {
      const settings = loadUserSettings();
      setDefaultModel(settings.defaultModel);
      setShowStaleBanner(settings.showStaleBanner);
    };

    window.addEventListener(USER_SETTINGS_CHANGED_EVENT, syncSettings);
    return () => {
      window.removeEventListener(USER_SETTINGS_CHANGED_EVENT, syncSettings);
    };
  }, []);

  const hasGeneratedRules = rules.length > 0;
  const hasRequirementSourceText = requirementText.trim().length > 0;
  const canEditRequirements = canUpdateWorkspace;
  const canRunGeneration = canUpdateWorkspace && canStartRuns;
  const editBlockedReason =
    workspacePermissionReason ?? "当前项目角色不能编辑需求内容。";
  const generationBlockedByPermissionReason =
    workspacePermissionReason ?? "当前项目角色不能启动生成。";

  const runGenerateRules = () => {
    if (!canRunGeneration) return;
    if (hasGeneratedRules) {
      setRuleReplacementDialogOpen(true);
      return;
    }
    void generateRules();
  };

  const confirmRuleReplacement = () => {
    setRuleReplacementDialogOpen(false);
    if (!canRunGeneration) return;
    void generateRules();
  };

  const runGenerateDiagrams = (only?: DiagramType[]) => {
    if (!canRunGeneration) return;
    void generateDiagrams(only);
  };

  const decideAutoReviews = (
    event: MouseEvent<HTMLButtonElement>,
    reviews: AutoGeneratedUpstreamReview[],
    decision: "accepted" | "dismissed",
  ) => {
    event.stopPropagation();
    void Promise.all(
      reviews.map((review) =>
        decideAutoGeneratedUpstreamReview(review.id, decision),
      ),
    );
  };

  const updateModel = (model: string) => {
    if (!canRunGeneration) return;
    patchUserSettings({ defaultModel: model });
  };

  const selectableDiagramSet = useMemo(() => new Set(DIAGRAM_ORDER), []);

  const toggleDiagram = (diagram: DiagramType, checked: boolean) => {
    if (!canEditRequirements) return;
    if (checked && !selectableDiagramSet.has(diagram)) {
      return;
    }
    setSelectedDiagrams(
      checked
        ? Array.from(new Set([...selectedDiagrams, diagram]))
        : selectedDiagrams.filter((value) => value !== diagram),
    );
  };

  useEffect(() => {
    const nextSelectedDiagrams = selectedDiagrams.filter((diagram) =>
      selectableDiagramSet.has(diagram),
    );
    if (nextSelectedDiagrams.length !== selectedDiagrams.length) {
      setSelectedDiagrams(nextSelectedDiagrams);
    }
  }, [selectableDiagramSet, selectedDiagrams, setSelectedDiagrams]);

  const toggleNewRuleDiagram = (diagram: DiagramType, checked: boolean) => {
    setNewRuleDiagrams((current) =>
      checked
        ? Array.from(new Set([...current, diagram]))
        : current.filter((value) => value !== diagram),
    );
  };

  const resetNewRuleForm = () => {
    setNewRuleCategory("功能需求");
    setNewRuleDiagrams(DEFAULT_NEW_RULE_DIAGRAMS);
    setNewRuleText("");
    setNewRuleError(null);
  };

  const submitNewRule = () => {
    const trimmedText = newRuleText.trim();
    if (!trimmedText) {
      setNewRuleError("请填写需求文本。");
      return;
    }
    if (newRuleDiagrams.length === 0) {
      setNewRuleError("请至少选择一个对应模型。");
      return;
    }
    createRequirementRule({
      category: newRuleCategory,
      relatedDiagrams: newRuleDiagrams,
      text: trimmedText,
    });
    setNewRuleDialogOpen(false);
    resetNewRuleForm();
  };

  const newRuleCanSubmit = newRuleText.trim().length > 0 && newRuleDiagrams.length > 0;

  const filteredRules = useMemo(() => {
    const normalizedQuery = query.trim().toLowerCase();
    return rules.filter((rule) => {
      const matchesQuery =
        !normalizedQuery || rule.text.toLowerCase().includes(normalizedQuery);
      const matchesCategory =
        ruleCategoryFilter === ALL_RULE_CATEGORIES ||
        rule.category === ruleCategoryFilter;
      return matchesQuery && matchesCategory;
    });
  }, [rules, query, ruleCategoryFilter]);

  useEffect(() => {
    setCurrentRulePage(1);
  }, [query, ruleCategoryFilter]);

  const totalRulePages = Math.max(1, Math.ceil(filteredRules.length / rulePageSize));
  const safeRulePage = Math.min(currentRulePage, totalRulePages);
  const firstRuleIndex =
    filteredRules.length === 0 ? 0 : (safeRulePage - 1) * rulePageSize + 1;
  const lastRuleIndex = Math.min(filteredRules.length, safeRulePage * rulePageSize);
  const pagedRules = filteredRules.slice(firstRuleIndex - 1, lastRuleIndex);
  const emptyRuleSlots = Math.max(0, rulePageSize - pagedRules.length);
  const requirementByRuleId = useMemo(() => {
    const entries =
      requirementBaseline?.requirements
        .filter((requirement) => requirement.sourceRuleId)
        .map((requirement) => [requirement.sourceRuleId!, requirement] as const) ?? [];
    return new Map(entries);
  }, [requirementBaseline]);
  const qualityIssuesByRequirementId = useMemo(() => {
    const map = new Map<string, RequirementQualityIssue[]>();
    for (const issue of requirementBaseline?.qualityReport.issues ?? []) {
      if (!issue.requirementId) continue;
      map.set(issue.requirementId, [
        ...(map.get(issue.requirementId) ?? []),
        issue,
      ]);
    }
    return map;
  }, [requirementBaseline]);
  const hintDetail = useMemo<RequirementHintDetail | null>(() => {
    if (!hintDetailRuleId) return null;
    const rule = rules.find((item) => item.id === hintDetailRuleId);
    const requirement = requirementByRuleId.get(hintDetailRuleId);
    if (!rule || !requirement) return null;
    const qualityIssues = qualityIssuesByRequirementId.get(requirement.id) ?? [];
    const fieldEntries = Object.entries(requirement.fieldProvenance).filter(
      (entry): entry is [
        AtomicRequirementField,
        NonNullable<AtomicRequirement["fieldProvenance"][AtomicRequirementField]>,
      ] => {
        const [, provenance] = entry;
        return Boolean(
          provenance &&
            (provenance.source === "ai-suggested" ||
              provenance.status === "pending-review" ||
              provenance.status === "rejected"),
        );
      },
    );
    return {
      rule,
      requirement,
      candidate: requirementReviewCandidates[hintDetailRuleId] ?? null,
      rowState: requirementRowState(requirement, qualityIssues),
      qualityIssues,
      fieldEntries,
    };
  }, [
    hintDetailRuleId,
    qualityIssuesByRequirementId,
    requirementByRuleId,
    requirementReviewCandidates,
    rules,
  ]);
  const lastHintDetailRef = useRef<typeof hintDetail>(null);
  if (hintDetail) {
    lastHintDetailRef.current = hintDetail;
  }
  const visibleHintDetail = hintDetailRuleId
    ? hintDetail ??
      (lastHintDetailRef.current?.rule.id === hintDetailRuleId
        ? lastHintDetailRef.current
        : null)
    : null;
  useEffect(() => {
    if (currentRulePage > totalRulePages) {
      setCurrentRulePage(totalRulePages);
    }
  }, [currentRulePage, totalRulePages]);

  const generateDiagramsButtonLabel = requirementDiagramsButtonLabel({
    generatedDiagrams,
    selectedDiagrams,
    staleDiagrams,
  });
  const generationBlockedTitle =
    requirementReviewBlockedReason ?? undefined;
  const selectedTargetBlockReason =
    selectedDiagrams
      .map((diagram) =>
        requirementTargetBlockReason({
          diagram,
          generatedDiagrams,
          hasRequirementSourceText,
          isRulesStale,
          rules,
          staleDiagrams,
        }),
      )
      .find(Boolean) ?? null;
  const requirementModelRepairRecords = useMemo(() => {
    return buildRequirementModelRepairRecords({
      generatedDiagrams,
      requirementModelTraceability,
      rules,
    });
  }, [generatedDiagrams, requirementModelTraceability, rules]);

  const renderRequirementInput = (mode: "empty" | "generated") => (
    <div
      className={cn(
        "relative",
        mode === "empty" &&
          "overflow-hidden rounded-xl border border-border bg-card p-6 shadow-sm",
      )}
    >
      {mode === "empty" && (
        <div className="absolute -right-20 -top-20 size-64 rounded-full bg-primary/5 blur-3xl" />
      )}
      <div className="relative flex items-center justify-between gap-4">
        <div className="flex items-center gap-2">
          <FileText className="size-5 text-primary" />
          <h2
            id="requirement-text-heading"
            className="text-xl font-semibold tracking-normal text-foreground"
          >
            {mode === "empty" ? "项目需求描述" : "需求描述"}
          </h2>
        </div>
      </div>
      <textarea
        id="requirement-text"
        aria-labelledby="requirement-text-heading"
        name="requirementText"
        value={requirementText}
        onChange={(event) => {
          if (canEditRequirements) setRequirementText(event.target.value);
        }}
        placeholder="用一段话描述你的系统：做什么、给谁用、有哪些角色和关键流程，越具体越能抽出准确的需求规则"
        disabled={!canEditRequirements}
        title={!canEditRequirements ? editBlockedReason : undefined}
        className={cn(
          "relative mt-3 w-full resize-y rounded-lg border border-input bg-background px-4 py-4 text-sm leading-relaxed text-foreground outline-none transition-colors placeholder:text-muted-foreground focus:border-primary/60 focus:ring-2 focus:ring-primary/15",
          !canEditRequirements &&
            "cursor-not-allowed bg-muted/40 text-muted-foreground",
          mode === "empty" ? "h-[clamp(360px,48vh,620px)] min-h-80" : "h-[240px]",
        )}
      />
      <ScaledToolbar
        minWidth={420}
        minReadableScale={0.7}
        className="relative mt-6"
        contentClassName="w-full gap-2"
      >
          <ModelPicker
            value={defaultModel}
            onValueChange={updateModel}
            disabled={!canRunGeneration}
          />
          {isRulesStale && (
            <Badge variant="warning" className="rounded-md px-1.5 py-0 text-[11px]">
              需求已修改
            </Badge>
          )}
          <div className="ml-auto flex items-center gap-2">
            <Button
              type="button"
              variant="outline"
              size="sm"
              className="h-10 rounded-full px-6"
              onClick={() => setRequirementText("")}
              disabled={!requirementText || generating || !canEditRequirements}
              title={!canEditRequirements ? editBlockedReason : undefined}
            >
              清空
            </Button>
            <button
              type="button"
              onClick={runGenerateRules}
              disabled={!requirementText.trim() || generating || !canRunGeneration}
              title={
                !canRunGeneration
                  ? generationBlockedByPermissionReason
                  : isRulesStale
                    ? "更新需求规则"
                    : "生成需求规则"
              }
              className="inline-flex h-10 items-center gap-2 rounded-full bg-primary px-6 text-sm font-medium text-primary-foreground shadow-sm transition-opacity hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-40"
            >
              {generating ? (
                <Loader2 className="size-4 animate-spin" />
              ) : (
                <ArrowUp className="size-4" />
              )}
              {isRulesStale ? "更新需求规则" : "开始分析提取"}
            </button>
          </div>
      </ScaledToolbar>
    </div>
  );

  const renderRequirementRules = () => (
    <RequirementRulesTable
      canEditRequirements={canEditRequirements}
      currentRulePage={currentRulePage}
      deleteRequirementRule={deleteRequirementRule}
      editBlockedReason={editBlockedReason}
      emptyRuleSlots={emptyRuleSlots}
      filteredRules={filteredRules}
      firstRuleIndex={firstRuleIndex}
      generating={generating}
      lastRuleIndex={lastRuleIndex}
      onAddRule={() => setNewRuleDialogOpen(true)}
      onOpenHintDetail={setHintDetailRuleId}
      pagedRules={pagedRules}
      qualityIssuesByRequirementId={qualityIssuesByRequirementId}
      query={query}
      requirementByRuleId={requirementByRuleId}
      requirementReviewCandidates={requirementReviewCandidates}
      ruleCategoryFilter={ruleCategoryFilter}
      rulePageSize={rulePageSize}
      rulesCount={rules.length}
      safeRulePage={safeRulePage}
      setCurrentRulePage={setCurrentRulePage}
      setQuery={setQuery}
      setRuleCategoryFilter={setRuleCategoryFilter}
      setRulePageSize={setRulePageSize}
      totalRulePages={totalRulePages}
      updateRequirementRule={updateRequirementRule}
    />
  );

  return (
    <div className="flex h-full min-h-0 min-w-0 max-w-full flex-col overflow-x-hidden overflow-y-auto bg-background">
      {showStaleBanner && isRulesStale && (
        <div className="flex items-center gap-2 border-b border-warning/40 bg-warning/10 px-3 py-2 text-sm">
          <AlertTriangle className="size-4 text-warning" />
          <span>需求文本已修改，下方规则基于旧文本，可能已过时。</span>
          <Button
            size="sm"
            variant="outline"
            className="ml-auto h-7"
            onClick={runGenerateRules}
            disabled={generating || !canRunGeneration}
            title={!canRunGeneration ? generationBlockedByPermissionReason : undefined}
          >
            <RefreshCw className="size-3.5" /> 重新生成规则
          </Button>
        </div>
      )}

      {showStaleBanner && staleDiagrams.length > 0 && (
        <div className="flex items-center gap-2 border-b border-warning/40 bg-warning/10 px-3 py-2 text-sm">
          <AlertTriangle className="size-4 text-warning" />
          <span>
            {staleDiagrams.length} 个模型基于旧规则：
            {staleDiagrams.map((diagram) => DIAGRAM_META[diagram].label).join("、")}
          </span>
          <Button
            size="sm"
            variant="outline"
            className="ml-auto h-7"
            onClick={() => runGenerateDiagrams(staleDiagrams)}
            disabled={
              generating ||
              Boolean(requirementReviewBlockedReason) ||
              !canRunGeneration
            }
            title={
              !canRunGeneration
                ? generationBlockedByPermissionReason
                : generationBlockedTitle
            }
          >
            <RefreshCw className="size-3.5" /> 仅更新过时模型
          </Button>
        </div>
      )}

      <div className="min-w-0 max-w-full overflow-x-hidden py-4 lg:py-5">
        <div className="mx-auto flex w-[calc(100%-1.5rem)] min-w-0 max-w-none flex-col gap-5 sm:w-[calc(100%-2rem)] lg:w-[calc(100%-3rem)]">
          <header className="flex flex-col gap-1.5">
            <h1 className="text-2xl font-semibold tracking-normal text-foreground lg:text-3xl">
              需求分析提取
            </h1>
            <p className="max-w-3xl text-sm leading-6 text-muted-foreground">
              输入您的项目需求描述，系统将帮助您提取关键用例、参与者并生成初始的系统模型。
            </p>
            {!canEditRequirements && (
              <div className="mt-2 inline-flex max-w-3xl items-center gap-2 rounded-lg border border-warning/30 bg-warning/10 px-3 py-2 text-xs text-warning">
                <AlertTriangle className="size-3.5" />
                {editBlockedReason}
              </div>
            )}
            {billingGenerationBlock && (
              <div className="mt-2 flex max-w-4xl flex-wrap items-center gap-3 rounded-lg border border-warning/30 bg-warning/10 px-3 py-2 text-sm text-foreground">
                <AlertTriangle className="size-4 text-warning" />
                <div className="min-w-0 flex-1">
                  <div className="font-medium">{billingGenerationBlock.message}</div>
                  <div className="text-xs text-muted-foreground">
                    可用次数 {billingGenerationBlock.billingSummary.creditBalance}，
                    {billingGenerationBlock.billingSummary.activePass
                      ? `通行卡今日 ${billingGenerationBlock.billingSummary.passDailyUsage.usedToday}/${billingGenerationBlock.billingSummary.passDailyUsage.limit}`
                      : "当前没有有效通行卡"}
                  </div>
                </div>
                <Button
                  type="button"
                  size="icon"
                  variant="ghost"
                  className="size-8"
                  aria-label="关闭权益提示"
                  onClick={clearBillingGenerationBlock}
                >
                  <X className="size-4" />
                </Button>
              </div>
            )}
          </header>
          <div className="grid min-w-0 max-w-full grid-cols-1 gap-4 overflow-x-hidden">
            <div className="grid min-w-0 grid-cols-[minmax(0,1fr)] gap-4">
              {renderRequirementInput(hasGeneratedRules ? "generated" : "empty")}
              {hasGeneratedRules && renderRequirementRules()}
            </div>
          </div>

          <section className="flex flex-col gap-4">
            <ScaledToolbar
              minWidth={500}
              minReadableScale={0.68}
              contentClassName="w-full justify-between gap-6"
            >
              <div className="flex shrink-0 items-center gap-2">
                <Network className="size-5 text-primary" />
                <h2 className="text-xl font-semibold tracking-normal text-foreground">
                  目标模型
                </h2>
                <Badge
                  variant="secondary"
                  className="rounded-md border-0 px-3 py-1 font-mono text-xs"
                >
                  {selectedDiagrams.length}/{DIAGRAM_ORDER.length}
                </Badge>
              </div>
              <div className="flex shrink-0 items-center gap-2">
                {requirementModelRepairRecords.length > 0 && (
                  <Button
                    type="button"
                    size="sm"
                    variant="outline"
                    className="h-9 rounded-lg bg-card"
                    aria-label={`查看需求模型追踪证明，共 ${requirementModelRepairRecords.length} 项`}
                    onClick={() => setTraceabilityDialogOpen(true)}
                  >
                    <Eye className="size-3.5" />
                    追踪证明
                    <span className="rounded border border-border bg-muted px-1.5 py-0.5 font-mono text-[10px]">
                      {requirementModelRepairRecords.length}项
                    </span>
                  </Button>
                )}
                <ModelPicker
                  value={defaultModel}
                  onValueChange={updateModel}
                  align="end"
                  triggerClassName="bg-card"
                  disabled={!canRunGeneration}
                />
                <button
                  type="button"
                  onClick={() => runGenerateDiagrams()}
                  disabled={
                    selectedDiagrams.length === 0 ||
                    generating ||
                    Boolean(requirementReviewBlockedReason) ||
                    Boolean(selectedTargetBlockReason) ||
                    !canRunGeneration
                  }
                  title={
                    !canRunGeneration
                      ? generationBlockedByPermissionReason
                      : selectedTargetBlockReason ?? generationBlockedTitle
                  }
                  className="inline-flex h-9 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-medium text-primary-foreground shadow-sm transition-opacity hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-40"
                >
                  {generating ? (
                    <Loader2 className="size-4 animate-spin" />
                  ) : (
                    <Wand2 className="size-4" />
                  )}
                  {generateDiagramsButtonLabel}
                </button>
              </div>
            </ScaledToolbar>
            {requirementReviewBlockedReason && (
              <div className="flex items-center gap-1.5 rounded-lg border border-warning/30 bg-warning/10 px-3 py-2 text-xs text-warning">
                <AlertTriangle className="size-3.5" />
                {requirementReviewBlockedReason}
              </div>
            )}

            <MobileCompactGrid
              minWidth={720}
              className="grid-cols-2 2xl:grid-cols-3"
            >
              {DIAGRAM_ORDER.map((diagram) => {
                const meta = DIAGRAM_META[diagram];
                const {
                  autoFillLabels,
                  blockReason,
                  canSelectDiagram,
                  checked,
                  hasPendingAutoReview,
                  isAnalysisDiagram,
                  linkedRules,
                  pendingAutoReviews,
                  sourceCount,
                } = requirementTargetCardState({
                  autoGeneratedUpstreamReviews,
                  canEditRequirements,
                  diagram,
                  generatedDiagrams,
                  hasRequirementSourceText,
                  isRulesStale,
                  rules,
                  selectedDiagrams,
                  staleDiagrams,
                });
                const DiagramIcon = REQUIREMENT_DIAGRAM_ICON[diagram];
                return (
                  <ModelBentoCard
                    key={diagram}
                    label={meta.label}
                    english={meta.english}
                    description={meta.description}
                    icon={DiagramIcon}
                    selected={checked}
                    disabled={!canSelectDiagram}
                    countLabel={sourceCount}
                    pendingReview={hasPendingAutoReview}
                    title={
                      !canEditRequirements ? editBlockedReason : undefined
                    }
                    ariaLabel={`${checked ? "取消选择" : "选择"}${meta.label}`}
                    checkboxLabel={meta.label}
                    onSelectedChange={(value) => toggleDiagram(diagram, value)}
                    status={
                      <div className="space-y-1.5">
                        {hasPendingAutoReview && (
                          <div className="rounded-md border border-warning/30 bg-warning/10 p-2 text-warning">
                            <div className="flex items-start gap-1.5">
                              <AlertTriangle className="mt-0.5 size-3.5 shrink-0" />
                              <span>
                                自动补齐待确认：
                                {pendingAutoReviews
                                  .map((review) => review.label)
                                  .join("、")}
                              </span>
                            </div>
                            <div className="mt-1 text-[11px] leading-relaxed">
                              缺少明确上游映射，系统仅临时补齐；可采纳、忽略或稍后处理。
                            </div>
                            <div className="mt-2 flex flex-wrap gap-2">
                              <Button
                                type="button"
                                size="sm"
                                variant="outline"
                                className="h-7 rounded-md px-2 text-[11px]"
                                aria-label={`采纳${meta.label}自动补齐`}
                                onClick={(event) =>
                                  decideAutoReviews(
                                    event,
                                    pendingAutoReviews,
                                    "accepted",
                                  )
                                }
                              >
                                采纳补齐
                              </Button>
                              <Button
                                type="button"
                                size="sm"
                                variant="ghost"
                                className="h-7 rounded-md px-2 text-[11px]"
                                aria-label={`忽略${meta.label}自动补齐`}
                                onClick={(event) =>
                                  decideAutoReviews(
                                    event,
                                    pendingAutoReviews,
                                    "dismissed",
                                  )
                                }
                              >
                                忽略提示
                              </Button>
                            </div>
                          </div>
                        )}
                        {!canSelectDiagram && (
                          <div className="flex items-center gap-1.5 text-destructive">
                            <AlertTriangle className="size-3.5 shrink-0" />
                            <span>
                              {blockReason ??
                                (isAnalysisDiagram
                                  ? "需先选择或生成用例模型"
                                  : "缺少对应需求规则")}
                            </span>
                          </div>
                        )}
                        {autoFillLabels.length > 0 && !blockReason && (
                          <div className="flex items-center gap-1.5 text-warning">
                            <AlertTriangle className="size-3.5 shrink-0" />
                            <span>将自动补齐：{autoFillLabels.join("、")}</span>
                          </div>
                        )}
                        {isAnalysisDiagram &&
                          canSelectDiagram &&
                          linkedRules.length === 0 && (
                            <div className="text-muted-foreground">
                              基于用例模型事件流生成，不要求需求规则直接映射。
                            </div>
                          )}
                        {canSelectDiagram &&
                          autoFillLabels.length === 0 &&
                          !(
                            isAnalysisDiagram && linkedRules.length === 0
                          ) && (
                            <div className="text-muted-foreground">
                              已关联来源：{sourceCount}
                            </div>
                          )}
                      </div>
                    }
                    details={
                      linkedRules.length > 0 ? (
                        <div className="hidden flex-wrap gap-1.5 sm:flex">
                          {linkedRules.map((rule) => (
                            <button
                              type="button"
                              key={rule.id}
                              title={rule.text}
                              onClick={(event) => {
                                event.stopPropagation();
                                const element = document.getElementById(
                                  `rule-${rule.id}`,
                                );
                                if (element) {
                                  element.scrollIntoView({
                                    behavior: "smooth",
                                    block: "center",
                                  });
                                  element.classList.add("ring-2", "ring-primary/40");
                                  setTimeout(() => {
                                    element.classList.remove(
                                      "ring-2",
                                      "ring-primary/40",
                                    );
                                  }, 1200);
                                }
                              }}
                              onKeyDown={(event) => event.stopPropagation()}
                              className="rounded border border-border bg-secondary px-2 py-0.5 font-mono text-[10px] uppercase text-muted-foreground transition-colors hover:border-primary/40 hover:bg-accent hover:text-accent-foreground"
                            >
                              {rule.id}
                            </button>
                          ))}
                        </div>
                      ) : null
                    }
                  />
                );
              })}
            </MobileCompactGrid>
            <p className="pb-4 text-center text-xs text-muted-foreground">
              勾选不会立即生效；点击「生成模型」后左侧菜单才会更新。之后生成需求模型、设计模型、代码原型和说明书时，都会优先使用这里选择的需求项。
            </p>
          </section>
        </div>
      </div>

      <RequirementReviewDialog
        generating={generating}
        onConfirmQualityHint={confirmRequirementQualityHint}
        onDecideReviewCandidate={decideRequirementReviewCandidate}
        onOpenChange={(open) => {
          if (!open) setHintDetailRuleId(null);
        }}
        onRepairRequirementRule={repairRequirementRule}
        visibleHintDetail={visibleHintDetail}
      />

      <RequirementTraceabilityDialogs
        modelRepairResult={modelRepairResult}
        records={requirementModelRepairRecords}
        setModelRepairResult={setModelRepairResult}
        setTraceabilityDialogOpen={setTraceabilityDialogOpen}
        traceabilityDialogOpen={traceabilityDialogOpen}
      />

      <Dialog
        open={ruleReplacementDialogOpen}
        onOpenChange={setRuleReplacementDialogOpen}
      >
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle>确认替换需求规则</DialogTitle>
            <DialogDescription>
              重新抽取会全量替换当前 {rules.length} 条需求规则；旧需求模型仍可查看，但不再匹配新规则的追踪映射会被清理，并需要重新生成下游模型。
            </DialogDescription>
          </DialogHeader>
          <DialogFooter className="gap-2 sm:gap-2">
            <Button
              type="button"
              variant="outline"
              onClick={() => setRuleReplacementDialogOpen(false)}
            >
              取消
            </Button>
            <Button
              type="button"
              onClick={confirmRuleReplacement}
              disabled={generating || !canRunGeneration}
            >
              确认替换
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <NewRequirementRuleDialog
        canEditRequirements={canEditRequirements}
        generating={generating}
        newRuleCanSubmit={newRuleCanSubmit}
        newRuleCategory={newRuleCategory}
        newRuleDiagrams={newRuleDiagrams}
        newRuleError={newRuleError}
        newRuleText={newRuleText}
        onCategoryChange={(category) => {
          setNewRuleCategory(category);
          setNewRuleError(null);
        }}
        onOpenChange={(open) => {
          setNewRuleDialogOpen(open);
          if (!open) resetNewRuleForm();
        }}
        onSubmit={submitNewRule}
        onTextChange={(text) => {
          setNewRuleText(text);
          setNewRuleError(null);
        }}
        onToggleDiagram={(diagram, checked) => {
          toggleNewRuleDiagram(diagram, checked);
          setNewRuleError(null);
        }}
        open={newRuleDialogOpen}
      />

    </div>
  );
}
