// Derives target-model card state and traceability proof rows for requirement generation.
import { DIAGRAM_META, type DiagramType } from "../../../entities/diagram/model";
import type { RequirementRule } from "../../../entities/requirement-rule/model";
import type { WorkspaceRecord } from "../../../entities/workspace/model";
import { pendingAutoReviewsForRequirementDiagram } from "./requirement-review-view-model";

export interface RequirementModelRepairRecord {
  id: string;
  reason: string;
  repair: string;
  targetLabel: string;
  status: string;
}

export interface RequirementTargetCardStateInput {
  autoGeneratedUpstreamReviews: WorkspaceRecord["autoGeneratedUpstreamReviews"];
  canEditRequirements: boolean;
  diagram: DiagramType;
  generatedDiagrams: DiagramType[];
  hasRequirementSourceText: boolean;
  isRulesStale: boolean;
  rules: RequirementRule[];
  selectedDiagrams: DiagramType[];
  staleDiagrams: DiagramType[];
}

export function requirementDiagramsButtonLabel(input: {
  generatedDiagrams: DiagramType[];
  selectedDiagrams: DiagramType[];
  staleDiagrams: DiagramType[];
}) {
  const { generatedDiagrams, selectedDiagrams, staleDiagrams } = input;
  const toAdd = selectedDiagrams.filter(
    (diagram) => !generatedDiagrams.includes(diagram),
  ).length;
  const toKeep = generatedDiagrams.filter(
    (diagram) => !selectedDiagrams.includes(diagram),
  ).length;
  const stale = staleDiagrams.filter((diagram) =>
    selectedDiagrams.includes(diagram),
  ).length;
  if (generatedDiagrams.length === 0) return "生成模型";
  const parts: string[] = [];
  if (toAdd) parts.push(`新增${toAdd}`);
  if (toKeep) parts.push(`保留${toKeep}`);
  if (stale) parts.push(`更新${stale}`);
  return parts.length ? `应用变更（${parts.join("·")}）` : "重新生成";
}

export function requirementTargetBlockReason(input: {
  diagram: DiagramType;
  generatedDiagrams: DiagramType[];
  hasRequirementSourceText: boolean;
  isRulesStale: boolean;
  rules: RequirementRule[];
  staleDiagrams: DiagramType[];
}) {
  const {
    diagram,
    generatedDiagrams,
    hasRequirementSourceText,
    isRulesStale,
    rules,
    staleDiagrams,
  } = input;
  if (isRulesStale && rules.length > 0) {
    return "需求规则已过期，请先更新需求规则";
  }
  if (rules.length === 0 && !hasRequirementSourceText) {
    const canGenerateAnalysisFromUseCase =
      diagram === "analysis" && generatedDiagrams.includes("usecase");
    if (!canGenerateAnalysisFromUseCase) {
      return "请先输入需求描述或添加需求规则";
    }
  }
  if (
    diagram === "analysis" &&
    generatedDiagrams.includes("usecase") &&
    staleDiagrams.includes("usecase")
  ) {
    return "用例模型已存在但基于旧规则，请先更新用例模型";
  }
  return null;
}

export function requirementTargetCardState(input: RequirementTargetCardStateInput) {
  const {
    autoGeneratedUpstreamReviews,
    canEditRequirements,
    diagram,
    generatedDiagrams,
    hasRequirementSourceText,
    isRulesStale,
    rules,
    selectedDiagrams,
    staleDiagrams,
  } = input;
  const checked = selectedDiagrams.includes(diagram);
  const linkedRules = rules.filter((rule) => rule.relatedDiagrams.includes(diagram));
  const isAnalysisDiagram = diagram === "analysis";
  const isExistingRequirementModel = generatedDiagrams.includes(diagram);
  const canGenerateSelectedUseCase =
    selectedDiagrams.includes("usecase") &&
    (rules.length > 0 || hasRequirementSourceText);
  const hasUseCaseSourceForAnalysis =
    generatedDiagrams.includes("usecase") || canGenerateSelectedUseCase;
  const blockReason = requirementTargetBlockReason({
    diagram,
    generatedDiagrams,
    hasRequirementSourceText,
    isRulesStale,
    rules,
    staleDiagrams,
  });
  const autoFillLabels = [
    !isAnalysisDiagram && rules.length === 0 && hasRequirementSourceText
      ? "需求规则"
      : null,
    !isAnalysisDiagram && rules.length > 0 && linkedRules.length === 0
      ? "规则映射"
      : null,
    isAnalysisDiagram && !hasUseCaseSourceForAnalysis
      ? DIAGRAM_META.usecase.label
      : null,
  ].filter((label): label is string => Boolean(label));
  const pendingAutoReviews = pendingAutoReviewsForRequirementDiagram(
    autoGeneratedUpstreamReviews,
    diagram,
  );
  return {
    autoFillLabels,
    blockReason,
    canSelectDiagram:
      canEditRequirements &&
      (!blockReason ||
        (isRulesStale && rules.length > 0 && isExistingRequirementModel)),
    checked,
    hasPendingAutoReview: pendingAutoReviews.length > 0,
    hasUseCaseSourceForAnalysis,
    isAnalysisDiagram,
    linkedRules,
    pendingAutoReviews,
    sourceCount: isAnalysisDiagram
      ? Number(hasUseCaseSourceForAnalysis)
      : linkedRules.length,
  };
}

export function buildRequirementModelRepairRecords(input: {
  generatedDiagrams: DiagramType[];
  requirementModelTraceability: WorkspaceRecord["requirementModelTraceability"];
  rules: RequirementRule[];
}): RequirementModelRepairRecord[] {
  const { generatedDiagrams, requirementModelTraceability, rules } = input;
  if (generatedDiagrams.length === 0 || requirementModelTraceability.length === 0) {
    return [];
  }
  return requirementModelTraceability.slice(0, 6).map((entry) => {
    const linkedRule = rules.find((rule) => rule.id === entry.ruleId);
    const targetDiagramLabel =
      entry.target.diagramKind in DIAGRAM_META
        ? DIAGRAM_META[entry.target.diagramKind as DiagramType].label
        : "需求模型";
    return {
      id: `${entry.ruleId}:${entry.target.diagramKind}:${entry.target.elementId}`,
      reason: linkedRule
        ? `需求规则 ${entry.ruleId} 需要解释其在${targetDiagramLabel}中的覆盖关系。`
        : `需求规则 ${entry.ruleId} 缺少可审查的模型覆盖解释。`,
      repair: `补齐 ${entry.ruleId} -> ${entry.target.label} 的追踪关系和覆盖说明`,
      targetLabel: `${targetDiagramLabel}：${entry.target.label}`,
      status: "证明已补齐",
    };
  });
}
