// Derives requirement review labels, tones, and field values for the authoring UI.
import type {
  AtomicRequirement,
  AtomicRequirementField,
  RequirementQualityIssue,
} from "@uml-platform/contracts";
import type { DiagramType } from "../../../entities/diagram/model";
import type { WorkspaceRecord } from "../../../entities/workspace/model";
import type { TFunction } from "i18next";

export const REQUIREMENT_FIELD_LABELS: Record<AtomicRequirementField, string> = {
  actor: "角色/执行者",
  subject: "主体",
  action: "动作",
  object: "对象",
  condition: "条件",
  outcome: "结果",
  acceptanceCriteria: "验收标准",
};

export const REVIEWABLE_REQUIREMENT_FIELDS = Object.keys(
  REQUIREMENT_FIELD_LABELS,
) as AtomicRequirementField[];

export type AutoGeneratedUpstreamReview =
  WorkspaceRecord["autoGeneratedUpstreamReviews"][string];

export function stageRepairCopy(text: string) {
  return text.replace(/\bAI\b\s*/gu, "系统");
}

export function requirementHintCount(requirement: AtomicRequirement | undefined) {
  if (!requirement) return 0;
  return Object.values(requirement.fieldProvenance).filter(
    (item) => item?.source === "ai-suggested" || item?.status === "pending-review",
  ).length;
}

export function requirementRowState(
  requirement: AtomicRequirement | undefined,
  qualityIssues: RequirementQualityIssue[] = [],
) {
  if (!requirement) return null;
  if (requirement.status === "conflict") return "存在冲突提示";
  const pendingAi = Object.values(requirement.fieldProvenance).some(
    (item) => item?.source === "ai-suggested" && item.status === "pending-review",
  );
  const rejectedOrManualPending = Object.values(requirement.fieldProvenance).some(
    (item) => item?.status === "rejected" || item?.status === "pending-review",
  );
  if (
    pendingAi ||
    rejectedOrManualPending ||
    qualityIssues.length > 0 ||
    requirement.status === "pending-review" ||
    requirement.status === "ambiguous"
  ) {
    return "有待确认提示";
  }
  const acceptedAi = Object.values(requirement.fieldProvenance).some(
    (item) => item?.source === "ai-suggested" && item.status === "accepted",
  );
  if (acceptedAi) return "已确认";
  return "已生成";
}

export function requirementStateTone(state: string | null) {
  if (state === "已生成") return "border-success/40 bg-success/10 text-success";
  if (state === "已确认") return "border-success/40 bg-success/10 text-success";
  if (state === "有待确认提示") return "border-warning/40 bg-warning/10 text-warning";
  if (state === "存在冲突提示") return "border-destructive/40 bg-destructive/10 text-destructive";
  return "border-border bg-muted/40 text-muted-foreground";
}

export function requirementFieldValue(
  requirement: AtomicRequirement,
  field: AtomicRequirementField,
) {
  const provenanceValue = requirement.fieldProvenance[field]?.value;
  if (typeof provenanceValue === "string" && provenanceValue.trim()) {
    return provenanceValue;
  }
  if (field === "acceptanceCriteria") {
    return requirement.acceptanceCriteria.join("；");
  }
  return requirement[field] ?? "";
}

export function requirementFieldStatusLabel(status: string, t?: TFunction) {
  if (status === "accepted") return t ? t("requirements.review.fieldStatus.accepted") : "已确认";
  if (status === "rejected") return t ? t("requirements.review.fieldStatus.rejected") : "已拒绝";
  return t ? t("requirements.review.fieldStatus.pending") : "待确认";
}

export function reviewCandidateStateLabel(
  candidate: WorkspaceRecord["requirementReviewCandidates"][string] | undefined,
  rowState: string | null,
) {
  if (candidate?.status === "failed") return "修复失败待重试";
  if (candidate?.status === "pending") return "修复结果待确认";
  if (candidate?.status === "accepted" || candidate?.status === "rejected") {
    return "已确认";
  }
  return rowState;
}

export function reviewCandidateDecisionLabel(
  candidate: WorkspaceRecord["requirementReviewCandidates"][string] | undefined,
) {
  if (candidate?.status === "accepted") return "已采纳修复";
  if (candidate?.status === "rejected") return "已拒绝修复";
  return null;
}

export function requirementSourceLabel(source: string, t?: TFunction) {
  if (source === "ai-suggested") return t ? t("requirements.review.sources.ai") : "AI补齐";
  if (source === "manual") return t ? t("requirements.review.sources.manual") : "手动编辑";
  if (source === "source-text") return t ? t("requirements.review.sources.source") : "原文提取";
  return t ? t("requirements.review.sources.inferred") : "规则推断";
}

export function pendingAutoReviewsForRequirementDiagram(
  reviews: WorkspaceRecord["autoGeneratedUpstreamReviews"],
  diagram: DiagramType,
): AutoGeneratedUpstreamReview[] {
  return Object.values(reviews).filter(
    (review) =>
      review.status === "pending" &&
      ((review.artifactType === "requirement-model" &&
        review.artifactId === diagram) ||
        (review.artifactType === "requirement-rule" &&
          review.artifactId === `mapping:${diagram}`)),
  );
}
