import type { ReactNode } from "react";
import { ThemeProvider } from "../app/providers/theme-provider";
import type {
  AtomicRequirement,
  RequirementBaseline,
  RunSnapshot,
} from "@uml-platform/contracts";
import type { RequirementRule } from "../entities/requirement-rule/model";
import type { WorkspaceRecord } from "../entities/workspace/model";
import { WorkspaceShellProvider } from "../features/workspace-shell/state";
import { WorkspaceSessionProvider } from "../features/workspace-session/state";
import { WorkspaceRepositoryProvider } from "../services/workspace-repository";
import type { WorkspaceRepository } from "../services/workspace-repository";
import type { DiagramType } from "../entities/diagram/model";
import { DEFAULT_USER_SETTINGS, USER_SETTINGS_STORAGE_KEY } from "../shared/lib/user-settings";

export function createWorkspaceRecord(
  overrides: Partial<WorkspaceRecord> = {},
): WorkspaceRecord {
  return {
    id: "workspace-test",
    name: "Test Workspace",
    requirementText: "",
    selectedDiagramTypes: [],
    rules: [],
    requirementBaseline: null,
    requirementQualityReport: null,
    requirementReviewCandidates: {},
    autoGeneratedUpstreamReviews: {},
    models: {},
    requirementModelTraceability: [],
    generatedDiagramTypes: [],
    plantUml: {},
    svgArtifacts: {},
    diagramErrors: {},
    selectedDesignDiagramTypes: [],
    designModels: {},
    designModelTraceability: [],
    generatedDesignDiagramTypes: [],
    designPlantUml: {},
    designSvgArtifacts: {},
    designDiagramErrors: {},
    manualModelEditStatus: {},
    codeSpec: null,
    codeBusinessLogic: null,
    codeFiles: {},
    codeEntryFile: null,
    codeDependencies: {},
    codeUiMockup: null,
    codeAgentPlan: [],
    codeSkills: [],
    codeSkillDiagnostics: [],
    codeSkillResourcePlan: null,
    codeSkillContext: null,
    codeDiagnostics: [],
    requirementInputFingerprint: null,
    diagramInputFingerprints: {},
    designInputFingerprints: {},
    rulesVersion: 0,
    rulesBasedOnTextVersion: null,
    diagramVersions: {},
    currentStage: null,
    runStatus: "idle",
    runProgress: 0,
    runMessage: null,
    errorMessage: null,
    ...overrides,
  };
}

export function createRule(
  overrides: Partial<RequirementRule> = {},
): RequirementRule {
  return {
    id: "r1",
    category: "业务规则",
    text: "用户必须登录后才能访问主要功能。",
    relatedDiagrams: ["usecase"],
    ...overrides,
  };
}

export function createRequirementBaseline(
  overrides: Partial<RequirementBaseline> = {},
): RequirementBaseline {
  const requirement: AtomicRequirement = {
    id: "REQ-001",
    sourceRuleId: "r1",
    sourceFragment: "用户必须登录后才能访问主要功能。",
    type: "functional",
    actor: "用户",
    subject: "用户",
    action: "访问",
    object: "主要功能",
    condition: "用户已登录",
    outcome: "系统允许访问主要功能",
    confidence: 0.9,
    status: "accepted",
    criticality: "high",
    acceptanceCriteria: ["用户登录后可以访问主要功能。"],
    fieldProvenance: {},
  };
  return {
    runId: "run-baseline",
    sourceDocumentId: "inline-requirement",
    createdAt: "2026-06-05T00:00:00.000Z",
    requirements: [requirement],
    assumptions: [],
    conflicts: [],
    qualityReport: {
      runId: "run-baseline",
      status: "passed",
      summary: "需求基线已确认。",
      issues: [],
      blockingIssueIds: [],
      reviewRequiredRequirementIds: [],
    },
    ...overrides,
  };
}

export function createRunSnapshot(
  overrides: Partial<RunSnapshot> = {},
): RunSnapshot {
  return {
    runId: "run-test",
    requirementText: "",
    selectedDiagrams: [],
    rules: [],
    models: [],
    plantUml: [],
    svgArtifacts: [],
    diagramErrors: {},
    requirementTrace: [],
    currentStage: "render_svg",
    status: "completed",
    errorMessage: null,
    ...overrides,
  };
}

export function withWorkspaceProviders(
  children: ReactNode,
  repository?: WorkspaceRepository,
) {
  if (!localStorage.getItem(USER_SETTINGS_STORAGE_KEY)) {
    localStorage.setItem(
      USER_SETTINGS_STORAGE_KEY,
      JSON.stringify(DEFAULT_USER_SETTINGS),
    );
  }

  return (
    <ThemeProvider>
      <WorkspaceShellProvider>
        <WorkspaceRepositoryProvider repository={repository}>
          <WorkspaceSessionProvider>{children}</WorkspaceSessionProvider>
        </WorkspaceRepositoryProvider>
      </WorkspaceShellProvider>
    </ThemeProvider>
  );
}

export function createDiagramVersions(
  entries: Array<[DiagramType, number]>,
): Partial<Record<DiagramType, number>> {
  return Object.fromEntries(entries) as Partial<Record<DiagramType, number>>;
}
