// Owns auto-generated upstream review persistence actions for the session provider.
import { useCallback, useState } from "react";
import type { WorkspaceRecord } from "../../../entities/workspace/model";
import type { WorkspaceRepository } from "../../../services/workspace-repository";

export function useAutoGeneratedUpstreamReviews(
  repository: WorkspaceRepository,
) {
  const [autoGeneratedUpstreamReviews, setAutoGeneratedUpstreamReviews] =
    useState<WorkspaceRecord["autoGeneratedUpstreamReviews"]>({});

  const persistAutoGeneratedUpstreamReviews = useCallback(
    async (reviews: WorkspaceRecord["autoGeneratedUpstreamReviews"]) => {
      setAutoGeneratedUpstreamReviews(reviews);
      await repository.updateAutoGeneratedUpstreamReviews?.(reviews);
    },
    [repository],
  );

  const decideAutoGeneratedUpstreamReview = useCallback(
    async (reviewId: string, decision: "accepted" | "dismissed") => {
      if (!autoGeneratedUpstreamReviews[reviewId]) return;
      const next = {
        ...autoGeneratedUpstreamReviews,
        [reviewId]: {
          ...autoGeneratedUpstreamReviews[reviewId],
          status: decision,
        },
      };
      await persistAutoGeneratedUpstreamReviews(next);
    },
    [autoGeneratedUpstreamReviews, persistAutoGeneratedUpstreamReviews],
  );

  const appendAutoGeneratedUpstreamReviews = useCallback(
    async (
      reviews: Array<WorkspaceRecord["autoGeneratedUpstreamReviews"][string]>,
    ) => {
      if (reviews.length === 0) return;
      const next = {
        ...autoGeneratedUpstreamReviews,
        ...Object.fromEntries(reviews.map((review) => [review.id, review])),
      };
      await persistAutoGeneratedUpstreamReviews(next);
    },
    [autoGeneratedUpstreamReviews, persistAutoGeneratedUpstreamReviews],
  );

  return {
    appendAutoGeneratedUpstreamReviews,
    autoGeneratedUpstreamReviews,
    decideAutoGeneratedUpstreamReview,
    setAutoGeneratedUpstreamReviews,
  };
}
