// Builds auto-generated upstream review records after generated dependencies complete.
import {
  DESIGN_DIAGRAM_META,
  DIAGRAM_META,
  type DesignDiagramType,
} from "../../../entities/diagram/model";
import type {
  WorkspaceDesignRunSnapshot,
  WorkspaceRecord,
  WorkspaceRunSnapshot,
} from "../../../entities/workspace/model";
import type { RequirementAutoUpstreamPlan } from "./generation-planning";
import { createAutoGeneratedUpstreamReview } from "./workspace-context";

type UpstreamReview =
  WorkspaceRecord["autoGeneratedUpstreamReviews"][string];

export function createRequirementGenerationUpstreamReviews(input: {
  modelSnapshot: WorkspaceRunSnapshot | null;
  plan: RequirementAutoUpstreamPlan;
  reviewedRuleIds: string[];
  rulesSnapshot: WorkspaceRunSnapshot | null;
}): UpstreamReview[] {
  const reviews: UpstreamReview[] = [];
  if (input.rulesSnapshot && input.plan.rulesRunMode === "replace") {
    for (const ruleId of input.reviewedRuleIds) {
      reviews.push(
        createAutoGeneratedUpstreamReview({
          artifactType: "requirement-rule",
          artifactId: ruleId,
          label: `需求规则 ${ruleId}`,
          reason: "生成所选模型时缺少可用需求规则，系统自动抽取/更新。",
          sourceRunId: input.rulesSnapshot.runId,
        }),
      );
    }
  }
  if (input.rulesSnapshot && input.plan.rulesRunMode === "merge") {
    for (const diagram of input.plan.ruleMappingDiagrams) {
      reviews.push(
        createAutoGeneratedUpstreamReview({
          artifactType: "requirement-rule",
          artifactId: `mapping:${diagram}`,
          label: `${DIAGRAM_META[diagram].label}规则映射`,
          reason: "生成所选模型时缺少上游规则映射，系统自动补齐关联关系。",
          sourceRunId: input.rulesSnapshot.runId,
        }),
      );
    }
  }
  if (input.modelSnapshot) {
    for (const diagram of input.plan.dependencyDiagrams) {
      reviews.push(
        createAutoGeneratedUpstreamReview({
          artifactType: "requirement-model",
          artifactId: diagram,
          label: DIAGRAM_META[diagram].label,
          reason: "生成所选需求模型时缺少前置上游模型，系统自动补齐。",
          sourceRunId: input.modelSnapshot.runId,
        }),
      );
    }
  }
  return reviews;
}

export function createDesignGenerationUpstreamReviews(input: {
  dependencyDiagrams: DesignDiagramType[];
  designSnapshot: WorkspaceDesignRunSnapshot | null;
  requirementModelSnapshot: WorkspaceRunSnapshot | null;
  requirementPlan: RequirementAutoUpstreamPlan;
  reviewedRuleIds: string[];
  rulesSnapshot: WorkspaceRunSnapshot | null;
}): UpstreamReview[] {
  const reviews: UpstreamReview[] = [];
  if (input.rulesSnapshot && input.requirementPlan.rulesRunMode === "replace") {
    for (const ruleId of input.reviewedRuleIds) {
      reviews.push(
        createAutoGeneratedUpstreamReview({
          artifactType: "requirement-rule",
          artifactId: ruleId,
          label: `需求规则 ${ruleId}`,
          reason: "生成设计模型时缺少可用需求规则，系统自动抽取/更新。",
          sourceRunId: input.rulesSnapshot.runId,
        }),
      );
    }
  }
  if (input.rulesSnapshot && input.requirementPlan.rulesRunMode === "merge") {
    for (const diagram of input.requirementPlan.ruleMappingDiagrams) {
      reviews.push(
        createAutoGeneratedUpstreamReview({
          artifactType: "requirement-rule",
          artifactId: `mapping:${diagram}`,
          label: `${DIAGRAM_META[diagram].label}规则映射`,
          reason: "生成设计模型时缺少上游规则映射，系统自动补齐关联关系。",
          sourceRunId: input.rulesSnapshot.runId,
        }),
      );
    }
  }
  if (input.requirementModelSnapshot) {
    for (const diagram of input.requirementPlan.effectiveDiagrams) {
      reviews.push(
        createAutoGeneratedUpstreamReview({
          artifactType: "requirement-model",
          artifactId: diagram,
          label: DIAGRAM_META[diagram].label,
          reason: "生成设计模型时缺少需求阶段上游模型，系统自动补齐。",
          sourceRunId: input.requirementModelSnapshot.runId,
        }),
      );
    }
  }
  if (input.designSnapshot) {
    for (const diagram of input.dependencyDiagrams) {
      reviews.push(
        createAutoGeneratedUpstreamReview({
          artifactType: "design-model",
          artifactId: diagram,
          label: DESIGN_DIAGRAM_META[diagram].label,
          reason: "生成所选设计模型时缺少设计阶段上游模型，系统自动补齐。",
          sourceRunId: input.designSnapshot.runId,
        }),
      );
    }
  }
  return reviews;
}
