// Applies persisted workspace records back into the workspace session slices.
import type { WorkspaceRecord } from "../../../entities/workspace/model";

type Setter<T> = (value: T) => void;

type RunUiState = {
  runStatus: WorkspaceRecord["runStatus"];
  runProgress: WorkspaceRecord["runProgress"];
  runMessage: WorkspaceRecord["runMessage"];
  errorMessage: WorkspaceRecord["errorMessage"];
};

type WorkspaceRecordAppliers = {
  setRequirementTextRaw: Setter<WorkspaceRecord["requirementText"]>;
  setRules: Setter<WorkspaceRecord["rules"]>;
  setRequirementBaseline: Setter<WorkspaceRecord["requirementBaseline"] | null>;
  setRequirementQualityReport: Setter<WorkspaceRecord["requirementQualityReport"] | null>;
  setRequirementReviewCandidates: Setter<WorkspaceRecord["requirementReviewCandidates"]>;
  setAutoGeneratedUpstreamReviews: Setter<WorkspaceRecord["autoGeneratedUpstreamReviews"]>;
  setModels: Setter<WorkspaceRecord["models"]>;
  setRequirementModelTraceability: Setter<WorkspaceRecord["requirementModelTraceability"]>;
  setSelectedDiagrams: Setter<WorkspaceRecord["selectedDiagramTypes"]>;
  setPlantUml: Setter<WorkspaceRecord["plantUml"]>;
  setSvgArtifacts: Setter<WorkspaceRecord["svgArtifacts"]>;
  setDiagramErrors: Setter<WorkspaceRecord["diagramErrors"]>;
  setSelectedDesignDiagrams: Setter<WorkspaceRecord["selectedDesignDiagramTypes"]>;
  setDesignModels: Setter<WorkspaceRecord["designModels"]>;
  setDesignModelTraceability: Setter<WorkspaceRecord["designModelTraceability"]>;
  setDesignPlantUml: Setter<WorkspaceRecord["designPlantUml"]>;
  setDesignSvgArtifacts: Setter<WorkspaceRecord["designSvgArtifacts"]>;
  setDesignDiagramErrors: Setter<WorkspaceRecord["designDiagramErrors"]>;
  setManualModelEditStatus: Setter<WorkspaceRecord["manualModelEditStatus"]>;
  setCodeSpec: Setter<WorkspaceRecord["codeSpec"]>;
  setCodeBusinessLogic: Setter<WorkspaceRecord["codeBusinessLogic"]>;
  setCodeFiles: Setter<WorkspaceRecord["codeFiles"]>;
  setCodeEntryFile: Setter<WorkspaceRecord["codeEntryFile"]>;
  setCodeDependencies: Setter<WorkspaceRecord["codeDependencies"]>;
  setCodeUiMockup: Setter<WorkspaceRecord["codeUiMockup"]>;
  setCodeAgentPlan: Setter<WorkspaceRecord["codeAgentPlan"]>;
  setCodeSkills: Setter<WorkspaceRecord["codeSkills"]>;
  setCodeSkillDiagnostics: Setter<WorkspaceRecord["codeSkillDiagnostics"]>;
  setCodeSkillResourcePlan: Setter<WorkspaceRecord["codeSkillResourcePlan"]>;
  setCodeSkillContext: Setter<WorkspaceRecord["codeSkillContext"]>;
  setCodeDiagnostics: Setter<WorkspaceRecord["codeDiagnostics"]>;
  setGeneratedDiagrams: Setter<WorkspaceRecord["generatedDiagramTypes"]>;
  setGeneratedDesignDiagrams: Setter<WorkspaceRecord["generatedDesignDiagramTypes"]>;
  setRulesVersion: Setter<WorkspaceRecord["rulesVersion"]>;
  setRulesBasedOnTextVersion: Setter<WorkspaceRecord["rulesBasedOnTextVersion"]>;
  setRequirementInputFingerprint: Setter<WorkspaceRecord["requirementInputFingerprint"] | null>;
  setDiagramVersions: Setter<WorkspaceRecord["diagramVersions"]>;
  setDiagramInputFingerprints: Setter<WorkspaceRecord["diagramInputFingerprints"]>;
  setDesignInputFingerprints: Setter<WorkspaceRecord["designInputFingerprints"]>;
  setRunUiState: Setter<RunUiState>;
  setTextVersion: Setter<number>;
};

export function applyWorkspaceRecordToSessionState(
  workspace: WorkspaceRecord,
  appliers: WorkspaceRecordAppliers,
) {
  appliers.setRequirementTextRaw(workspace.requirementText);
  appliers.setRules(workspace.rules);
  appliers.setRequirementBaseline(workspace.requirementBaseline ?? null);
  appliers.setRequirementQualityReport(workspace.requirementQualityReport ?? null);
  appliers.setRequirementReviewCandidates(workspace.requirementReviewCandidates ?? {});
  appliers.setAutoGeneratedUpstreamReviews(
    workspace.autoGeneratedUpstreamReviews ?? {},
  );
  appliers.setModels(workspace.models);
  appliers.setRequirementModelTraceability(
    workspace.requirementModelTraceability ?? [],
  );
  appliers.setSelectedDiagrams([]);
  appliers.setPlantUml(workspace.plantUml);
  appliers.setSvgArtifacts(workspace.svgArtifacts);
  appliers.setDiagramErrors(workspace.diagramErrors);
  appliers.setSelectedDesignDiagrams([]);
  appliers.setDesignModels(workspace.designModels);
  appliers.setDesignModelTraceability(workspace.designModelTraceability ?? []);
  appliers.setDesignPlantUml(workspace.designPlantUml);
  appliers.setDesignSvgArtifacts(workspace.designSvgArtifacts);
  appliers.setDesignDiagramErrors(workspace.designDiagramErrors);
  appliers.setManualModelEditStatus(workspace.manualModelEditStatus ?? {});
  appliers.setCodeSpec(workspace.codeSpec);
  appliers.setCodeBusinessLogic(workspace.codeBusinessLogic);
  appliers.setCodeFiles(workspace.codeFiles);
  appliers.setCodeEntryFile(workspace.codeEntryFile);
  appliers.setCodeDependencies(workspace.codeDependencies);
  appliers.setCodeUiMockup(workspace.codeUiMockup);
  appliers.setCodeAgentPlan(workspace.codeAgentPlan);
  appliers.setCodeSkills(workspace.codeSkills);
  appliers.setCodeSkillDiagnostics(workspace.codeSkillDiagnostics);
  appliers.setCodeSkillResourcePlan(workspace.codeSkillResourcePlan);
  appliers.setCodeSkillContext(workspace.codeSkillContext);
  appliers.setCodeDiagnostics(workspace.codeDiagnostics);
  appliers.setGeneratedDiagrams(workspace.generatedDiagramTypes);
  appliers.setGeneratedDesignDiagrams(workspace.generatedDesignDiagramTypes);
  appliers.setRulesVersion(workspace.rulesVersion);
  appliers.setRulesBasedOnTextVersion(workspace.rulesBasedOnTextVersion);
  appliers.setRequirementInputFingerprint(
    workspace.requirementInputFingerprint ?? null,
  );
  appliers.setDiagramVersions(workspace.diagramVersions);
  appliers.setDiagramInputFingerprints(workspace.diagramInputFingerprints ?? {});
  appliers.setDesignInputFingerprints(workspace.designInputFingerprints ?? {});
  appliers.setRunUiState({
    runStatus: workspace.runStatus,
    runProgress: workspace.runProgress,
    runMessage: workspace.runMessage,
    errorMessage: workspace.errorMessage,
  });
  appliers.setTextVersion(0);
}
